/content/gallery/visitscotland/default:
  jcr:primaryType: hippogallery:stdImageGallery
  hippostd:foldertype: [new-visitscotland-Image-folder]
  hippostd:gallerytype: ['visitscotland:Image']
  /vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: 1e4be246-297b-4404-8102-80fe1bc0ddf7
    /vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:description: ''
      hippogallery:filename: vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg
      visitscotland:altText: ''
      visitscotland:credit: ''
      visitscotland:location: Edinburgh
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg
        hippogallery:height: 40
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg/vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2019-12-10T15:49:45.047Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 194
        hippogallery:width: 288
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg/vector-illustration-of-cartoon-hippos-in-hot-weather-drawing_csp36829792.jpg/original/original.jpg
        jcr:lastModified: 2019-12-10T15:49:45.047Z
        jcr:mimeType: image/jpeg
  /fraserburgh---davron-hotel-6.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: 9fb38865-ca10-4ef4-bcab-a1097cc44487
    hippo:name: Fraserburgh - Davron Hotel (6).jpg
    /fraserburgh---davron-hotel-6.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:description: ''
      hippogallery:filename: Fraserburgh - Davron Hotel (6).jpg
      visitscotland:altText: ''
      visitscotland:credit: ''
      visitscotland:location: Largs
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: Fraserburgh - Davron Hotel (6).jpg
        hippogallery:height: 40
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/fraserburgh---davron-hotel-6.jpg/fraserburgh---davron-hotel-6.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2019-12-11T11:31:30.522Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 1281
        hippogallery:width: 1920
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/fraserburgh---davron-hotel-6.jpg/fraserburgh---davron-hotel-6.jpg/original/original.jpg
        jcr:lastModified: 2019-12-11T11:31:30.522Z
        jcr:mimeType: image/jpeg
  /visitscotland_49386435364-1.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
    hippo:name: visitscotland_49386435364 (1).jpg
    /visitscotland_49386435364-1.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:description: Man looking forward to finish this itinerary
      hippogallery:filename: visitscotland_49386435364 (1).jpg
      visitscotland:altText: He is also lost
      visitscotland:credit: VisitScotland Staff
      visitscotland:location: Glasgow
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: visitscotland_49386435364 (1).jpg
        hippogallery:height: 40
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/visitscotland_49386435364-1.jpg/visitscotland_49386435364-1.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2019-12-11T11:31:44.652Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 1281
        hippogallery:width: 1920
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/visitscotland_49386435364-1.jpg/visitscotland_49386435364-1.jpg/original/original.jpg
        jcr:lastModified: 2019-12-11T11:31:44.652Z
        jcr:mimeType: image/jpeg
  /visitscotland_42559983584.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: f846ac14-4bbe-43af-8bdd-1f60979abc11
    /visitscotland_42559983584.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:description: ''
      hippogallery:filename: visitscotland_42559983584.jpg
      visitscotland:altText: ''
      visitscotland:credit: ''
      visitscotland:location: Edinburgh - City Centre
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: visitscotland_42559983584.jpg
        hippogallery:height: 40
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/visitscotland_42559983584.jpg/visitscotland_42559983584.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2020-02-26T08:55:15.199Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 1280
        hippogallery:width: 1920
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/visitscotland_42559983584.jpg/visitscotland_42559983584.jpg/original/original.jpg
        jcr:lastModified: 2020-02-26T08:55:15.199Z
        jcr:mimeType: image/jpeg
  /visitscotland_43424542162.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: 901a0eff-02b0-4cf8-bd34-92bf8c606c85
    /visitscotland_43424542162.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:description: ''
      hippogallery:filename: visitscotland_43424542162.jpg
      visitscotland:altText: ''
      visitscotland:credit: ''
      visitscotland:location: Abernyte
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: visitscotland_43424542162.jpg
        hippogallery:height: 40
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/visitscotland_43424542162.jpg/visitscotland_43424542162.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2020-02-26T08:55:15.951Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 1281
        hippogallery:width: 1920
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/visitscotland_43424542162.jpg/visitscotland_43424542162.jpg/original/original.jpg
        jcr:lastModified: 2020-02-26T08:55:15.951Z
        jcr:mimeType: image/jpeg
  /royal-botanic-garden.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: ecede5a4-326c-4ce5-b9be-bcdf32c3f2c2
    hippo:name: Royal Botanic Garden.jpg
    /royal-botanic-garden.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:filename: Royal Botanic Garden.jpg
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: Royal Botanic Garden.jpg
        hippogallery:height: 45
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/royal-botanic-garden.jpg/royal-botanic-garden.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2020-03-03T10:26:48.136Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 1536
        hippogallery:width: 2048
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/royal-botanic-garden.jpg/royal-botanic-garden.jpg/original/original.jpg
        jcr:lastModified: 2020-03-03T10:26:48.136Z
        jcr:mimeType: image/jpeg
  /header-iconicviewpoints.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: 878bc413-07fe-4c1a-9df6-55514c250a16
    /header-iconicviewpoints.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:description: Bealach na Bà, Applecross
      hippogallery:filename: header-iconicviewpoints.jpg
      visitscotland:altText: ''
      visitscotland:credit: Kenny Lam
      visitscotland:location: Applecross
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: header-iconicviewpoints.jpg
        hippogallery:height: 23
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/header-iconicviewpoints.jpg/header-iconicviewpoints.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2020-03-17T11:21:33.976Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 800
        hippogallery:width: 2048
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/header-iconicviewpoints.jpg/header-iconicviewpoints.jpg/original/original.jpg
        jcr:lastModified: 2020-03-17T11:21:33.976Z
        jcr:mimeType: image/jpeg
  /scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: f0fe0f26-489b-4a2e-b6c5-605df1abbdcb
    hippo:name: Scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg
    /scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg:
      jcr:primaryType: visitscotland:Image
      hippo:availability: [live, preview]
      hippogallery:filename: Scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg
      /hippogallery:thumbnail:
        jcr:primaryType: hippogallery:image
        hippo:filename: Scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg
        hippogallery:height: 40
        hippogallery:width: 60
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg/scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg/thumbnail/thumbnail.jpg
        jcr:lastModified: 2020-03-17T11:33:58.272Z
        jcr:mimeType: image/jpeg
      /hippogallery:original:
        jcr:primaryType: hippogallery:image
        hippogallery:height: 400
        hippogallery:width: 600
        jcr:data:
          type: binary
          resource: /content/gallery/visitscotland/default/scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg/scotts--view-lothar-stobbe-instagram-lairdsphotography.jpg/original/original.jpg
        jcr:lastModified: 2020-03-17T11:33:58.272Z
        jcr:mimeType: image/jpeg
