version: 2
updates:
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "yarn"
      directory: "/ui-integration"
      schedule:
          interval: "daily"