/content/gallery/bsh/default:
  jcr:primaryType: hippogallery:stdImageGallery
  jcr:mixinTypes: ['mix:versionable']
  jcr:uuid: e6fddb34-e750-424e-942b-9231ea979288
  hippostd:foldertype: [new-visitscotland-Image-folder]
  hippostd:gallerytype: ['visitscotland:Image']
