/content/documents/administration/configuration/seo-configuration-business-events:
  .meta:order-before: seo-configuration---support
  jcr:primaryType: hippo:handle
  jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
  jcr:uuid: 8de0e949-b822-4fb3-868f-a567415726cd
  hippo:name: SEO Configuration - Business Events
  hippo:versionHistory: 0eebad43-7079-4b3f-8773-bc6b87a8a710
  /seo-configuration-business-events[1]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: d816d6d0-6905-4c49-b960-49d6f6f455a0
    hippo:availability: []
    hippostd:retainable: false
    hippostd:state: draft
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2025-04-03T22:52:20.289+01:00
    hippostdpubwf:lastModificationDate: 2025-04-03T22:52:20.290+01:00
    hippostdpubwf:lastModifiedBy: admin
    resourcebundle:descriptions: ['']
    resourcebundle:id: be.seo
    resourcebundle:keys: [title-suffix]
    resourcebundle:messages: ['| VisitScotland Business Events']
  /seo-configuration-business-events[2]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
    jcr:uuid: 60ba777c-3d11-44a7-9692-011e3a732b5f
    hippo:availability: [preview]
    hippostd:retainable: false
    hippostd:state: unpublished
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2025-04-03T22:52:20.289+01:00
    hippostdpubwf:lastModificationDate: 2025-04-03T22:53:21.021+01:00
    hippostdpubwf:lastModifiedBy: admin
    resourcebundle:descriptions: ['']
    resourcebundle:id: be.seo
    resourcebundle:keys: [title-suffix]
    resourcebundle:messages: ['| VisitScotland Business Events']
  /seo-configuration-business-events[3]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: 0d0b6e72-2c87-413c-ad68-6fd8fe2a4741
    hippo:availability: [live]
    hippostd:retainable: false
    hippostd:state: published
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2025-04-03T22:52:20.289+01:00
    hippostdpubwf:lastModificationDate: 2025-04-03T22:53:21.021+01:00
    hippostdpubwf:lastModifiedBy: admin
    hippostdpubwf:publicationDate: 2025-04-03T22:53:41.943+01:00
    resourcebundle:descriptions: ['']
    resourcebundle:id: be.seo
    resourcebundle:keys: [title-suffix]
    resourcebundle:messages: ['| VisitScotland Business Events']
