/hst:hst/hst:configurations/business-events/hst:workspace/hst:sitemenus/main/services:
  .meta:order-before: key-sectors
  jcr:primaryType: hst:sitemenuitem
  hst:referencesitemapitem: pagenotfound
  hst:repobased: false
