/content/documents/visitscotland/site:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
    jcr:uuid: e8d415ec-a08a-478c-bb98-2605a2854e47
    hippostd:foldertype: [new-translated-folder, new-document]
    hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
    hippotranslation:locale: en