/content/documents/visitscotland/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: e8d415ec-a08a-478c-bb98-2605a2854e47
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: en
  /destinations-maps:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 81bb0b87-c15c-475d-bd13-5d9a262a95e5
    hippostd:foldertype: [new-translated-folder, new-document]
    hippotranslation:id: 9a465810-0318-447d-af80-28f023b96f0f
    hippotranslation:locale: en
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: 0751c1d3-3024-4d2d-a5e8-38286fee9722
      hippo:versionHistory: 49ebfb4a-7f18-4b26-b3ad-1571298fca3a
      /content[1]:
        jcr:primaryType: visitscotland:Itinerary
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: bfc6a747-1993-4871-991c-e203c3dff91c
        hippo:availability: []
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:17:51.970Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: a3ed9022-e239-493b-952c-18d01ac36640
        hippotranslation:locale: en
        visitscotland:areas: [The Highlands]
        visitscotland:breadcrumb: ''
        visitscotland:distance: 10.1
        visitscotland:finish: ''
        visitscotland:heading: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
        visitscotland:highlights: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\
          \n\r\nGlen Etive\r\n\r\nThe Elephant House"
        visitscotland:noIndex: false
        visitscotland:popular: false
        visitscotland:seoNoIndex: Follow in the footsteps of Harry Potter! Relive
          some of the films' most iconic scenes with our 4-day itinerary of Harry
          Potter sites in Scotland.
        visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
        visitscotland:start: ''
        visitscotland:summary: ''
        visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\n\
          Glen Etive\r\n\r\nThe Elephant House"
        visitscotland:theme: tv-film
        visitscotland:transport: [boat]
        visitscotland:transports: [car, train]
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>It was in Scotland's capital city that JK Rowling started
            to plot the adventures of Harry and his friends. With cobbled streets,
            winding alleys and medieval architecture, the city certainly has a few
            things in common with the settings from the books and films. She wrote
            the early chapters in various cafés around the city's Old Town, before
            coming back to finish off the series from a peaceful suite in The Balmoral
            Hotel. It is also said that Hogwarts School was styled on Edinburgh’s
            Fettes College, a private school on the outskirts of Edinburgh’s west
            end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
            World of Edinburgh</a> tour.</p>
      /content[2]:
        jcr:primaryType: visitscotland:Itinerary
        jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
        jcr:uuid: 54a5dc71-947d-4c5a-958c-9f06bebad234
        hippo:availability: [preview]
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:19:33.052Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: a3ed9022-e239-493b-952c-18d01ac36640
        hippotranslation:locale: en
        visitscotland:areas: [The Highlands]
        visitscotland:breadcrumb: ''
        visitscotland:distance: 10.1
        visitscotland:finish: ''
        visitscotland:heading: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
        visitscotland:highlights: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\
          \n\r\nGlen Etive\r\n\r\nThe Elephant House"
        visitscotland:noIndex: false
        visitscotland:popular: false
        visitscotland:seoNoIndex: Follow in the footsteps of Harry Potter! Relive
          some of the films' most iconic scenes with our 4-day itinerary of Harry
          Potter sites in Scotland.
        visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
        visitscotland:start: ''
        visitscotland:summary: ''
        visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\n\
          Glen Etive\r\n\r\nThe Elephant House"
        visitscotland:theme: tv-film
        visitscotland:transport: [boat]
        visitscotland:transports: [car, train]
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>It was in Scotland's capital city that JK Rowling started
            to plot the adventures of Harry and his friends. With cobbled streets,
            winding alleys and medieval architecture, the city certainly has a few
            things in common with the settings from the books and films. She wrote
            the early chapters in various cafés around the city's Old Town, before
            coming back to finish off the series from a peaceful suite in The Balmoral
            Hotel. It is also said that Hogwarts School was styled on Edinburgh’s
            Fettes College, a private school on the outskirts of Edinburgh’s west
            end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
            World of Edinburgh</a> tour.</p>
      /content[3]:
        jcr:primaryType: visitscotland:Itinerary
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 2dcf9013-726c-426b-adfb-c27786713726
        hippo:availability: [live]
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:13:47.279Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2019-12-12T12:14:37.338Z
        hippotranslation:id: a3ed9022-e239-493b-952c-18d01ac36640
        hippotranslation:locale: en
        visitscotland:areas: [The Highlands]
        visitscotland:breadcrumb: ''
        visitscotland:distance: 10.1
        visitscotland:finish: ''
        visitscotland:heading: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
        visitscotland:highlights: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\
          \n\r\nGlen Etive\r\n\r\nThe Elephant House"
        visitscotland:noIndex: false
        visitscotland:popular: false
        visitscotland:seoNoIndex: Follow in the footsteps of Harry Potter! Relive
          some of the films' most iconic scenes with our 4-day itinerary of Harry
          Potter sites in Scotland.
        visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
        visitscotland:start: ''
        visitscotland:summary: ''
        visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\n\
          Glen Etive\r\n\r\nThe Elephant House"
        visitscotland:theme: tv-film
        visitscotland:transport: [boat]
        visitscotland:transports: [car, train]
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <p>It's hard to believe that June 2019 was the 22nd anniversary of JK Rowling publishing her debut novel, Harry Potter and the Philosopher's Stone. In 1997, no one could have predicted the wildly successful book sales and box office smashing blockbusters that would follow.</p>

            <p>Still waiting for your letter to arrive by owl? Don't worry. You can immerse yourself in the wizarding world of Harry Potter by following this spellbinding four-day itinerary.</p>

            <p>Here in Scotland, you can see where Edinburgh-dweller JK Rowling found her inspiration - where the magic all began!</p>
    /edinburgh:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: 8ac72449-609b-45aa-b2b6-d3cb81a24139
      hippo:name: Edinburgh
      hippo:versionHistory: f29f8d11-003e-4baa-92cf-e74886a6e9ea
      /edinburgh[1]:
        jcr:primaryType: visitscotland:Day
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 0ffbb12c-63cd-4459-ba5d-d73822b10120
        hippo:availability: []
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-10T13:28:39.550Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:16:38.380Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 58eba379-722b-43b6-85c5-a58cffa5d53d
        hippotranslation:locale: en
        visitscotland:title: Edinburgh
        visitscotland:transports: [walking, car, train]
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>It was in Scotland's capital city that JK Rowling started
            to plot the adventures of Harry and his friends. With cobbled streets,
            winding alleys and medieval architecture, the city certainly has a few
            things in common with the settings from the books and films. She wrote
            the early chapters in various cafés around the city's Old Town, before
            coming back to finish off the series from a peaceful suite in The Balmoral
            Hotel. It is also said that Hogwarts School was styled on Edinburgh’s
            Fettes College, a private school on the outskirts of Edinburgh’s west
            end new town. You could also try the Wizarding World of Edinburgh tour.</p>
        /visitscotland:stops[1]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ca56dfe6-f8c8-410f-aa63-ed513fc71385
        /visitscotland:stops[2]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 28abd074-5fc4-4ebc-a424-1d4f9e5cb0e6
        /visitscotland:stops[3]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 1ead4399-7e30-47dc-9b75-2ea488fb5742
      /edinburgh[2]:
        jcr:primaryType: visitscotland:Day
        jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
        jcr:uuid: 8faffb50-41aa-4bd3-a841-75166d4ee460
        hippo:availability: [preview]
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-10T13:28:39.550Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:16:42.624Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 58eba379-722b-43b6-85c5-a58cffa5d53d
        hippotranslation:locale: en
        visitscotland:title: Edinburgh
        visitscotland:transports: [walking, car, train]
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>It was in Scotland's capital city that JK Rowling started
            to plot the adventures of Harry and his friends. With cobbled streets,
            winding alleys and medieval architecture, the city certainly has a few
            things in common with the settings from the books and films. She wrote
            the early chapters in various cafés around the city's Old Town, before
            coming back to finish off the series from a peaceful suite in The Balmoral
            Hotel. It is also said that Hogwarts School was styled on Edinburgh’s
            Fettes College, a private school on the outskirts of Edinburgh’s west
            end new town. You could also try the Wizarding World of Edinburgh tour.</p>
        /visitscotland:stops[1]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ca56dfe6-f8c8-410f-aa63-ed513fc71385
        /visitscotland:stops[2]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 28abd074-5fc4-4ebc-a424-1d4f9e5cb0e6
        /visitscotland:stops[3]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 1ead4399-7e30-47dc-9b75-2ea488fb5742
      /edinburgh[3]:
        jcr:primaryType: visitscotland:Day
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: ca79ffa1-5ca3-44d8-a2fd-1b2f017c995e
        hippo:availability: [live]
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-10T13:28:39.550Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:16:42.624Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2019-12-12T12:16:47.706Z
        hippotranslation:id: 58eba379-722b-43b6-85c5-a58cffa5d53d
        hippotranslation:locale: en
        visitscotland:title: Edinburgh
        visitscotland:transports: [walking, car, train]
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>It was in Scotland's capital city that JK Rowling started
            to plot the adventures of Harry and his friends. With cobbled streets,
            winding alleys and medieval architecture, the city certainly has a few
            things in common with the settings from the books and films. She wrote
            the early chapters in various cafés around the city's Old Town, before
            coming back to finish off the series from a peaceful suite in The Balmoral
            Hotel. It is also said that Hogwarts School was styled on Edinburgh’s
            Fettes College, a private school on the outskirts of Edinburgh’s west
            end new town. You could also try the Wizarding World of Edinburgh tour.</p>
        /visitscotland:stops[1]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ca56dfe6-f8c8-410f-aa63-ed513fc71385
        /visitscotland:stops[2]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 28abd074-5fc4-4ebc-a424-1d4f9e5cb0e6
        /visitscotland:stops[3]:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 1ead4399-7e30-47dc-9b75-2ea488fb5742
    /day-2:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: e48273b9-7b42-4456-837f-e014dc069d95
      hippo:name: day 2
      hippo:versionHistory: 330a5457-8af6-4549-abc4-aeba2388869c
      /day-2[1]:
        jcr:primaryType: visitscotland:Day
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 8d068d19-9845-40ea-80fe-4dc7dd0e95f7
        hippo:availability: []
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-12T12:06:04.129Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:06:23.090Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 2af219fa-878e-435f-ae2e-e296a16e21a9
        hippotranslation:locale: en
        visitscotland:title: ''
        visitscotland:transports: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>day 2</p>
      /day-2[2]:
        jcr:primaryType: visitscotland:Day
        jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
        jcr:uuid: 31bac8af-c240-4a3c-b982-f0006a5f111e
        hippo:availability: [preview]
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-12T12:06:04.129Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:06:10.150Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 2af219fa-878e-435f-ae2e-e296a16e21a9
        hippotranslation:locale: en
        visitscotland:title: ''
        visitscotland:transports: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>day 2</p>
      /day-2[3]:
        jcr:primaryType: visitscotland:Day
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 29a330bf-91ba-413d-9f7c-76dd55cc5b82
        hippo:availability: [live]
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2019-12-12T12:06:04.129Z
        hippostdpubwf:lastModificationDate: 2019-12-12T12:06:10.150Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2019-12-12T12:07:38.368Z
        hippotranslation:id: 2af219fa-878e-435f-ae2e-e296a16e21a9
        hippotranslation:locale: en
        visitscotland:title: ''
        visitscotland:transports: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>day 2</p>
