/content/documents/visitscotland/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: e8d415ec-a08a-478c-bb98-2605a2854e47
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: en
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: c0e6cfc5-53fa-4a5f-89dd-9b23624d08a4
    hippo:name: Home Page
    hippo:versionHistory: e975117f-b938-481e-a64d-d0a8927290ba
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 0c486965-1409-46d2-a8e5-119bfc2eab62
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-02-25T10:20:44.023Z
      hippostdpubwf:lastModifiedBy: editor
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Scotland, yours to enjoy. Responsibly.
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Let’s head back out and explore a little further with awe-inspiring landmarks and coastal seascapes for the perfect break.</p>

          <p>We’ll be exploring responsibly. Getting off the beaten track and away from busy spots, parking properly, closing gates and tidying up after ourselves.</p>

          <p>Once we’ve had our countryside fill, it’s time to enjoy one of our seven cultural cities, with their iconic attractions, relaxing accommodation choices, and innovative bars and restaurants.</p>

          <p>Then maybe a coastal seaside retreat with miles of sandy beaches during our extended <a href="https://www.visitscotland.com/about/themed-years/coasts-waters/" title="YOCW 2020">Scotland's Year of Coasts &amp; Waters</a>?</p>

          <p>After all, we deserve some quality time to ourselves, and with our friends and family.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: e51def55-8ed3-4eae-80df-1066a1eaff92
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-02-25T10:20:55.512Z
      hippostdpubwf:lastModifiedBy: editor
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Scotland, yours to enjoy. Responsibly.
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Let’s head back out and explore a little further with awe-inspiring landmarks and coastal seascapes for the perfect break.</p>

          <p>We’ll be exploring responsibly. Getting off the beaten track and away from busy spots, parking properly, closing gates and tidying up after ourselves.</p>

          <p>Once we’ve had our countryside fill, it’s time to enjoy one of our seven cultural cities, with their iconic attractions, relaxing accommodation choices, and innovative bars and restaurants.</p>

          <p>Then maybe a coastal seaside retreat with miles of sandy beaches during our extended <a href="https://www.visitscotland.com/about/themed-years/coasts-waters/" title="YOCW 2020">Scotland's Year of Coasts &amp; Waters</a>?</p>

          <p>After all, we deserve some quality time to ourselves, and with our friends and family.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 3cc9b54e-5dc1-46bc-a1b0-f1c13bc14432
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-02-25T10:20:55.512Z
      hippostdpubwf:lastModifiedBy: editor
      hippostdpubwf:publicationDate: 2022-02-25T10:27:21.552Z
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Scotland, yours to enjoy. Responsibly.
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Let’s head back out and explore a little further with awe-inspiring landmarks and coastal seascapes for the perfect break.</p>

          <p>We’ll be exploring responsibly. Getting off the beaten track and away from busy spots, parking properly, closing gates and tidying up after ourselves.</p>

          <p>Once we’ve had our countryside fill, it’s time to enjoy one of our seven cultural cities, with their iconic attractions, relaxing accommodation choices, and innovative bars and restaurants.</p>

          <p>Then maybe a coastal seaside retreat with miles of sandy beaches during our extended <a href="https://www.visitscotland.com/about/themed-years/coasts-waters/" title="YOCW 2020">Scotland's Year of Coasts &amp; Waters</a>?</p>

          <p>After all, we deserve some quality time to ourselves, and with our friends and family.</p>
