/content/documents/bsh/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: fa1f25ac-1048-413b-bc81-22435661195b
  hippostd:foldertype: [new-bsh-folder, new-bsh-page, new-bsh-module]
  hippotranslation:id: 28c7e5c6-7121-476b-9a92-5333c81e8e75
  hippotranslation:locale: en
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: ee0715f9-9c14-4fc9-8bc1-6d5a997eddad
    hippo:name: content
    hippo:versionHistory: df9a59e1-3d31-4979-8b99-b66720b631d3
    /content[1]:
      jcr:primaryType: visitscotland:GeneralBSH
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: 4532306a-b252-48e8-8934-65ad35f5f7b0
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-10-23T17:35:33.017+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 8bb7ab4c-379a-4dc5-8584-a46841ca1fd2
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Hidden
      visitscotland:publishDate: 0001-01-01T12:00:00Z
      visitscotland:readingTime: 0
      visitscotland:regions: []
      visitscotland:sectors: []
      visitscotland:seoDescription: Welcome to VisitScotland Business Events. Your
        partners in Scotland for conferences, conventions, meetings, incentives and
        more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: Welcome to Business Support Hub
      visitscotland:skill: ''
      visitscotland:teaser: Welcome to Business Support Hub.
      visitscotland:theme: top-level
      visitscotland:title: Welcome to Business Support Hub
      visitscotland:translation: ''
      visitscotland:type: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: c6adc092-756e-447d-861e-54a217b297d4
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>For years Scotland has welcomed the world's greatest thinkers, pioneers, innovators and leaders to the many international congresses, conferences and meetings we host. Scotland is an incredible destination for business events. Our world leading academia, research institutes, industries and innovation centres thrive on ideas, new challenges and the inspiration we can give and draw from delegates to our country.</p>

          <p>In Scotland we believe business events are a catalyst for social and economic transformation; they are a driver to tackle climate change; they are a voice for human rights; they are a leader in the global <a href="https://businessevents.visitscotland.com/why-scotland/journey-to-change/" title="Journey to change">Journey to Change</a>.</p>
    /content[2]:
      jcr:primaryType: visitscotland:GeneralBSH
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: bf7b68de-5dcd-459b-84a9-6810887cea7a
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-10-23T17:35:09.798+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 8bb7ab4c-379a-4dc5-8584-a46841ca1fd2
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Hidden
      visitscotland:publishDate: 0001-01-01T12:00:00Z
      visitscotland:readingTime: 0
      visitscotland:regions: []
      visitscotland:sectors: []
      visitscotland:seoDescription: Welcome to VisitScotland Business Events. Your
        partners in Scotland for conferences, conventions, meetings, incentives and
        more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: Welcome to Business Support Hub
      visitscotland:skill: ''
      visitscotland:teaser: Welcome to Business Support Hub.
      visitscotland:theme: top-level
      visitscotland:title: Welcome to Business Support Hub
      visitscotland:translation: ''
      visitscotland:type: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: c6adc092-756e-447d-861e-54a217b297d4
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>For years Scotland has welcomed the world's greatest thinkers, pioneers, innovators and leaders to the many international congresses, conferences and meetings we host. Scotland is an incredible destination for business events. Our world leading academia, research institutes, industries and innovation centres thrive on ideas, new challenges and the inspiration we can give and draw from delegates to our country.</p>

          <p>In Scotland we believe business events are a catalyst for social and economic transformation; they are a driver to tackle climate change; they are a voice for human rights; they are a leader in the global <a href="https://businessevents.visitscotland.com/why-scotland/journey-to-change/" title="Journey to change">Journey to Change</a>.</p>
    /content[3]:
      jcr:primaryType: visitscotland:GeneralBSH
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 95c2f8ed-3224-4be0-b127-c0714d3d28c3
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-10-23T17:35:33.017+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2024-10-23T17:58:48.385+01:00
      hippotranslation:id: 8bb7ab4c-379a-4dc5-8584-a46841ca1fd2
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Hidden
      visitscotland:publishDate: 0001-01-01T12:00:00Z
      visitscotland:readingTime: 0
      visitscotland:regions: []
      visitscotland:sectors: []
      visitscotland:seoDescription: Welcome to VisitScotland Business Events. Your
        partners in Scotland for conferences, conventions, meetings, incentives and
        more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: Welcome to Business Support Hub
      visitscotland:skill: ''
      visitscotland:teaser: Welcome to Business Support Hub.
      visitscotland:theme: top-level
      visitscotland:title: Welcome to Business Support Hub
      visitscotland:translation: ''
      visitscotland:type: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: c6adc092-756e-447d-861e-54a217b297d4
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>For years Scotland has welcomed the world's greatest thinkers, pioneers, innovators and leaders to the many international congresses, conferences and meetings we host. Scotland is an incredible destination for business events. Our world leading academia, research institutes, industries and innovation centres thrive on ideas, new challenges and the inspiration we can give and draw from delegates to our country.</p>

          <p>In Scotland we believe business events are a catalyst for social and economic transformation; they are a driver to tackle climate change; they are a voice for human rights; they are a leader in the global <a href="https://businessevents.visitscotland.com/why-scotland/journey-to-change/" title="Journey to change">Journey to Change</a>.</p>
  /site-search-results:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 950545d6-0836-46be-b2bc-d6e3c47cc259
    hippostd:foldertype: [new-bsh-folder, new-bsh-page, new-bsh-module]
    hippotranslation:id: 387ec8a1-c9c3-4fbe-8731-405c480963c8
    hippotranslation:locale: en
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: f30ad8c7-2eea-41b7-aebc-03cf4c261107
      hippo:name: Search results
      hippo:versionHistory: 1b43d945-bb9e-4b44-b719-a489f6ff4d7f
      /content[1]:
        jcr:primaryType: visitscotland:GeneralBSH
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: f54ad27c-afaa-4719-b989-1ff286e151a6
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2024-12-09T15:03:44.994Z
        hippostdpubwf:lastModificationDate: 2024-12-09T15:14:14.479Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: a45d2aef-2a61-4e3d-ab29-08b837bfcf97
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: true
        visitscotland:publishDate: 0001-01-01T12:00:00Z
        visitscotland:readingTime: 0
        visitscotland:regions: []
        visitscotland:sectors: []
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:skill: ''
        visitscotland:teaser: Search results
        visitscotland:theme: simple
        visitscotland:title: Search results
        visitscotland:topic: []
        visitscotland:type: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[2]:
        jcr:primaryType: visitscotland:GeneralBSH
        jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
        jcr:uuid: 9d1a10fb-64d1-49a9-affd-c7c137c25b2f
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2024-12-09T15:03:44.994Z
        hippostdpubwf:lastModificationDate: 2024-12-09T15:14:24.235Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: a45d2aef-2a61-4e3d-ab29-08b837bfcf97
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: true
        visitscotland:publishDate: 0001-01-01T12:00:00Z
        visitscotland:readingTime: 0
        visitscotland:regions: []
        visitscotland:sectors: []
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:skill: ''
        visitscotland:teaser: Search results
        visitscotland:theme: simple
        visitscotland:title: Search results
        visitscotland:topic: []
        visitscotland:type: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[3]:
        jcr:primaryType: visitscotland:GeneralBSH
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 0573d5e0-c732-44f2-bc95-dd3050648c81
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2024-12-09T15:03:44.994Z
        hippostdpubwf:lastModificationDate: 2024-12-09T15:14:24.235Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2024-12-09T15:14:28.246Z
        hippotranslation:id: a45d2aef-2a61-4e3d-ab29-08b837bfcf97
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: true
        visitscotland:publishDate: 0001-01-01T12:00:00Z
        visitscotland:readingTime: 0
        visitscotland:regions: []
        visitscotland:sectors: []
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:skill: ''
        visitscotland:teaser: Search results
        visitscotland:theme: simple
        visitscotland:title: Search results
        visitscotland:topic: []
        visitscotland:type: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
