/content/documents/www.visitscotland.com-it/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 34c2d00b-c612-4545-8438-728fc1c25714
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: it
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 624513c3-6cf0-4284-83b4-437493f0ea88
    hippo:name: Home Page (IT)
    hippo:versionHistory: 7f00a6f8-1c11-4bd0-82b0-c752d1a8b496
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: c2e7b141-3543-49b0-98d0-3d8dd8c26d31
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T09:53:58.201+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: it
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Default
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Benvenuti In Scozia
      visitscotland:theme: Standard
      visitscotland:title: Preparati per la Scozia
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Per una vacanza perfetta visita virtualmente la nostra campagna, le colline, i paesaggi vari, i monumenti storici ispiranti e le località marine.</p>

          <p>Prenditi il tempo necessario per visitare una di queste sette città della cultura, con le loro attrazioni turistiche famose, l'ampia scelta di alloggi, i bar ed i ristoranti che offrono anche servizi di takeaway o di consegna, a seconda delle restrizioni in vigore.</p>

          <p>Perché non fai un weekend al mare tra le miglia e miglia di spiagge di sabbia che puoi trovare nelle vicinanze nell'Anno delle Coste e <a href="https://www.visitscotland.com/it-it/about/themed-years/coasts-waters/" title="Anno delle Coste e delle Acque">delle Acque della Scozia</a>? Oppure perché non fai una vacanza in campeggio ed utilizzi il tempo e la quiete che puoi trovare nel cuore della campagna Scozzese per rafforzare il legame con i tuoi cari?</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: f9a741d2-fc3c-462e-9043-42ad7438ec5c
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T09:53:54.773+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: it
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Default
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Benvenuti In Scozia
      visitscotland:theme: Standard
      visitscotland:title: Preparati per la Scozia
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Per una vacanza perfetta visita virtualmente la nostra campagna, le colline, i paesaggi vari, i monumenti storici ispiranti e le località marine.</p>

          <p>Prenditi il tempo necessario per visitare una di queste sette città della cultura, con le loro attrazioni turistiche famose, l'ampia scelta di alloggi, i bar ed i ristoranti che offrono anche servizi di takeaway o di consegna, a seconda delle restrizioni in vigore.</p>

          <p>Perché non fai un weekend al mare tra le miglia e miglia di spiagge di sabbia che puoi trovare nelle vicinanze nell'Anno delle Coste e <a href="https://www.visitscotland.com/it-it/about/themed-years/coasts-waters/" title="Anno delle Coste e delle Acque">delle Acque della Scozia</a>? Oppure perché non fai una vacanza in campeggio ed utilizzi il tempo e la quiete che puoi trovare nel cuore della campagna Scozzese per rafforzare il legame con i tuoi cari?</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a77f5cfd-0f85-4e78-a263-e40947c39e45
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T09:53:58.201+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2024-06-21T09:53:59.642+01:00
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: it
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Default
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Benvenuti In Scozia
      visitscotland:theme: Standard
      visitscotland:title: Preparati per la Scozia
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Per una vacanza perfetta visita virtualmente la nostra campagna, le colline, i paesaggi vari, i monumenti storici ispiranti e le località marine.</p>

          <p>Prenditi il tempo necessario per visitare una di queste sette città della cultura, con le loro attrazioni turistiche famose, l'ampia scelta di alloggi, i bar ed i ristoranti che offrono anche servizi di takeaway o di consegna, a seconda delle restrizioni in vigore.</p>

          <p>Perché non fai un weekend al mare tra le miglia e miglia di spiagge di sabbia che puoi trovare nelle vicinanze nell'Anno delle Coste e <a href="https://www.visitscotland.com/it-it/about/themed-years/coasts-waters/" title="Anno delle Coste e delle Acque">delle Acque della Scozia</a>? Oppure perché non fai una vacanza in campeggio ed utilizzi il tempo e la quiete che puoi trovare nel cuore della campagna Scozzese per rafforzare il legame con i tuoi cari?</p>
  /site-search-results:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 6a969183-654a-48a4-a7e0-d9a61761ac55
    hippo:name: search-results
    hippostd:foldertype: [new-translated-folder, new-page, new-module]
    hippotranslation:id: ff87714b-7240-4eab-b6bd-12b1ff545ee3
    hippotranslation:locale: it
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: bd1ab9a2-4798-46d9-b6a5-39a0468dc778
      hippo:name: Search results (IT)
      hippo:versionHistory: e895700a-c646-4b2d-9b84-275de4743195
      /content[1]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:versionable']
        jcr:uuid: a16ef22d-9a1f-4d91-b136-5952d1d61edd
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:13.026Z
        hippostdpubwf:lastModificationDate: 2024-06-21T09:54:19.050+01:00
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: it
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[2]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 58d0ab22-e857-4b62-b0a9-9447b0a0310b
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:13.026Z
        hippostdpubwf:lastModificationDate: 2024-06-21T09:54:19.050+01:00
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2024-06-21T09:54:22.515+01:00
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: it
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[3]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: c1566828-8348-45f4-9b27-ce77ecff9bde
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:13.026Z
        hippostdpubwf:lastModificationDate: 2024-06-21T09:54:16.373+01:00
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: it
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
