/content/documents/www.visitscotland.com-it/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 34c2d00b-c612-4545-8438-728fc1c25714
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: it
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 624513c3-6cf0-4284-83b4-437493f0ea88
    hippo:name: Home Page (IT)
    hippo:versionHistory: d43b7eaa-417c-4662-9caf-3a218da21b75
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: c2e7b141-3543-49b0-98d0-3d8dd8c26d31
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:35:30.120+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: it
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Benvenuti In Scozia
      visitscotland:theme: Standard
      visitscotland:title: Preparati per la Scozia
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Per una vacanza perfetta visita virtualmente la nostra campagna, le colline, i paesaggi vari, i monumenti storici ispiranti e le località marine.</p>

          <p>Prenditi il tempo necessario per visitare una di queste sette città della cultura, con le loro attrazioni turistiche famose, l'ampia scelta di alloggi, i bar ed i ristoranti che offrono anche servizi di takeaway o di consegna, a seconda delle restrizioni in vigore.</p>

          <p>Perché non fai un weekend al mare tra le miglia e miglia di spiagge di sabbia che puoi trovare nelle vicinanze nell'Anno delle Coste e <a href="https://www.visitscotland.com/it-it/about/themed-years/coasts-waters/" title="Anno delle Coste e delle Acque">delle Acque della Scozia</a>? Oppure perché non fai una vacanza in campeggio ed utilizzi il tempo e la quiete che puoi trovare nel cuore della campagna Scozzese per rafforzare il legame con i tuoi cari?</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: f9a741d2-fc3c-462e-9043-42ad7438ec5c
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:35:30.191+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: it
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Benvenuti In Scozia
      visitscotland:theme: Standard
      visitscotland:title: Preparati per la Scozia
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Per una vacanza perfetta visita virtualmente la nostra campagna, le colline, i paesaggi vari, i monumenti storici ispiranti e le località marine.</p>

          <p>Prenditi il tempo necessario per visitare una di queste sette città della cultura, con le loro attrazioni turistiche famose, l'ampia scelta di alloggi, i bar ed i ristoranti che offrono anche servizi di takeaway o di consegna, a seconda delle restrizioni in vigore.</p>

          <p>Perché non fai un weekend al mare tra le miglia e miglia di spiagge di sabbia che puoi trovare nelle vicinanze nell'Anno delle Coste e <a href="https://www.visitscotland.com/it-it/about/themed-years/coasts-waters/" title="Anno delle Coste e delle Acque">delle Acque della Scozia</a>? Oppure perché non fai una vacanza in campeggio ed utilizzi il tempo e la quiete che puoi trovare nel cuore della campagna Scozzese per rafforzare il legame con i tuoi cari?</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a77f5cfd-0f85-4e78-a263-e40947c39e45
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:35:30.120+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2021-06-29T17:35:33.803+01:00
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: it
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Benvenuti In Scozia
      visitscotland:theme: Standard
      visitscotland:title: Preparati per la Scozia
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Per una vacanza perfetta visita virtualmente la nostra campagna, le colline, i paesaggi vari, i monumenti storici ispiranti e le località marine.</p>

          <p>Prenditi il tempo necessario per visitare una di queste sette città della cultura, con le loro attrazioni turistiche famose, l'ampia scelta di alloggi, i bar ed i ristoranti che offrono anche servizi di takeaway o di consegna, a seconda delle restrizioni in vigore.</p>

          <p>Perché non fai un weekend al mare tra le miglia e miglia di spiagge di sabbia che puoi trovare nelle vicinanze nell'Anno delle Coste e <a href="https://www.visitscotland.com/it-it/about/themed-years/coasts-waters/" title="Anno delle Coste e delle Acque">delle Acque della Scozia</a>? Oppure perché non fai una vacanza in campeggio ed utilizzi il tempo e la quiete che puoi trovare nel cuore della campagna Scozzese per rafforzare il legame con i tuoi cari?</p>
