spring.profiles.active=@spring.profiles.active@
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
springdoc.api-docs.path=/openapi/v1.json
springdoc.swagger-ui.path=/swagger-ui