/content/documents/www.visitscotland.com-es/site:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 6ff398fa-629f-400e-8af2-fcb37460ac6a
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: es
  /dev-test:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 70671ec3-13d3-4605-9b1e-c190f7eb5bd0
    hippostd:foldertype: [new-translated-folder, new-document]
    hippotranslation:id: 0ff458fa-cab8-47ba-9862-d8a0b7a1bacf
    hippotranslation:locale: es
    /itinerary:
      jcr:primaryType: hippostd:folder
      jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
      jcr:uuid: 81de15b7-8f82-4498-b579-48f8a60f945c
      hippostd:foldertype: [new-translated-folder, new-document]
      hippotranslation:id: 50c3b9d8-4fd6-460c-a3a6-cea7c7c00f01
      hippotranslation:locale: es
      /content:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
        jcr:uuid: 90473dc1-52c0-44c2-a153-964ce71ac713
        hippo:name: Itinerario
        hippo:versionHistory: b293eb82-c012-4260-9dcb-2ef03a53358e
        /content[1]:
          jcr:primaryType: visitscotland:Itinerary
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: 1285e8e9-e7b3-4547-90c4-6b8c5a53abad
          hippo:availability: [preview]
          hippostd:state: unpublished
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
          hippostdpubwf:lastModificationDate: 2020-07-03T13:57:21.477+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippotranslation:id: 56cf92c8-5887-4146-ad53-eaa062f4e07a
          hippotranslation:locale: es
          visitscotland:areas: [east, north]
          visitscotland:breadcrumb: Hola
          visitscotland:distance: 10.4
          visitscotland:finish: Ocean point
          visitscotland:highlights: "Glenfinnan Viaduct \r\nJacobite Steam Train\r\
            \nGlen Etive\r\nThe Elephant House"
          visitscotland:popular: false
          visitscotland:seoDescription: It was in Scotland's capital city that JK
            Rowling started to plot the adventures of Harry and his friends. With
            cobbled streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:seoNoIndex: false
          visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
          visitscotland:start: Tenerife
          visitscotland:summary: ''
          visitscotland:teaser: It was in Scotland's capital city that JK Rowling
            started to plot the adventures of Harry and his friends. With cobbled
            streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\
            \nGlen Etive\r\n\r\nThe Elephant House"
          visitscotland:theme: whisky
          visitscotland:title: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
          visitscotland:transport: [boat]
          visitscotland:transports: [car, train]
          /visitscotland:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              have a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
              World of Edinburgh</a> tour.</p>
          /visitscotland:ProductsSearch:
            jcr:primaryType: visitscotland:ProductsSearch
            visitscotland:distance: 0
            visitscotland:dmsCategories: [guesthouse, yurts, touringpark, hostel]
            visitscotland:dmscategories: ''
            visitscotland:location: ''
            visitscotland:producttype: ''
        /content[2]:
          jcr:primaryType: visitscotland:Itinerary
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 202d8d28-9ea4-4c11-8fef-abb67c616a61
          hippo:availability: []
          hippostd:state: draft
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
          hippostdpubwf:lastModificationDate: 2020-07-03T13:57:55.850+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippotranslation:id: 56cf92c8-5887-4146-ad53-eaa062f4e07a
          hippotranslation:locale: es
          visitscotland:areas: [east, north]
          visitscotland:breadcrumb: Hola
          visitscotland:distance: 10.4
          visitscotland:finish: Ocean point
          visitscotland:highlights: "Glenfinnan Viaduct \r\nJacobite Steam Train\r\
            \nGlen Etive\r\nThe Elephant House"
          visitscotland:popular: false
          visitscotland:seoDescription: It was in Scotland's capital city that JK
            Rowling started to plot the adventures of Harry and his friends. With
            cobbled streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:seoNoIndex: false
          visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
          visitscotland:start: Tenerife
          visitscotland:summary: ''
          visitscotland:teaser: It was in Scotland's capital city that JK Rowling
            started to plot the adventures of Harry and his friends. With cobbled
            streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\
            \nGlen Etive\r\n\r\nThe Elephant House"
          visitscotland:theme: whisky
          visitscotland:title: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
          visitscotland:transport: [boat]
          visitscotland:transports: [car, train]
          /visitscotland:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              have a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
              World of Edinburgh</a> tour.</p>
          /visitscotland:ProductsSearch:
            jcr:primaryType: visitscotland:ProductsSearch
            visitscotland:distance: 0
            visitscotland:dmsCategories: [guesthouse, yurts, touringpark, hostel]
            visitscotland:dmscategories: ''
            visitscotland:location: ''
            visitscotland:producttype: ''
        /content[3]:
          jcr:primaryType: visitscotland:Itinerary
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 927cc6ed-e57a-4bd8-9eac-ccbae638e186
          hippo:availability: [live]
          hippostd:state: published
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
          hippostdpubwf:lastModificationDate: 2020-07-03T13:57:21.477+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippostdpubwf:publicationDate: 2020-07-03T13:58:06.600+01:00
          hippotranslation:id: 56cf92c8-5887-4146-ad53-eaa062f4e07a
          hippotranslation:locale: es
          visitscotland:areas: [east, north]
          visitscotland:breadcrumb: Hola
          visitscotland:distance: 10.4
          visitscotland:finish: Ocean point
          visitscotland:highlights: "Glenfinnan Viaduct \r\nJacobite Steam Train\r\
            \nGlen Etive\r\nThe Elephant House"
          visitscotland:popular: false
          visitscotland:seoDescription: It was in Scotland's capital city that JK
            Rowling started to plot the adventures of Harry and his friends. With
            cobbled streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:seoNoIndex: false
          visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
          visitscotland:start: Tenerife
          visitscotland:summary: ''
          visitscotland:teaser: It was in Scotland's capital city that JK Rowling
            started to plot the adventures of Harry and his friends. With cobbled
            streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\
            \nGlen Etive\r\n\r\nThe Elephant House"
          visitscotland:theme: whisky
          visitscotland:title: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
          visitscotland:transport: [boat]
          visitscotland:transports: [car, train]
          /visitscotland:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              have a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
              World of Edinburgh</a> tour.</p>
          /visitscotland:ProductsSearch:
            jcr:primaryType: visitscotland:ProductsSearch
            visitscotland:distance: 0
            visitscotland:dmsCategories: [guesthouse, yurts, touringpark, hostel]
            visitscotland:dmscategories: ''
            visitscotland:location: ''
            visitscotland:producttype: ''
      /edimburgo:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
        jcr:uuid: 8035d846-d856-4aed-8b91-27f43549e953
        hippo:name: Edimburgo
        hippo:versionHistory: 15fa3e5c-36c4-4008-ab15-41390467aedd
        /edimburgo[1]:
          jcr:primaryType: visitscotland:Day
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: 57f075e8-c4e8-4425-b83f-8f5fc34d31ae
          hippo:availability: [preview]
          hippostd:state: unpublished
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-10T13:28:39.550Z
          hippostdpubwf:lastModificationDate: 2020-07-03T13:57:49.398+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippotranslation:id: 533c98b2-c2cd-491f-929a-ea2c4a491bb2
          hippotranslation:locale: es
          visitscotland:title: DMS Stops Day
          visitscotland:transports: [car, train, walking]
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              has a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the Wizarding World
              of Edinburgh tour.</p>
          /visitscotland:stops[1]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 8b215960-87aa-47ae-9c11-8a750be25ad8
          /visitscotland:stops[2]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: fb585bd7-188e-4430-a332-bf0fbc337d23
          /visitscotland:stops[3]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: ca56dfe6-f8c8-410f-aa63-ed513fc71385
          /visitscotland:stops[4]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 28abd074-5fc4-4ebc-a424-1d4f9e5cb0e6
        /edimburgo[2]:
          jcr:primaryType: visitscotland:Day
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 27337b04-7967-4f9b-81f7-4e6c807dc280
          hippo:availability: []
          hippostd:state: draft
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-10T13:28:39.550Z
          hippostdpubwf:lastModificationDate: 2020-07-03T13:57:57.670+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippotranslation:id: 533c98b2-c2cd-491f-929a-ea2c4a491bb2
          hippotranslation:locale: es
          visitscotland:title: DMS Stops Day
          visitscotland:transports: [car, train, walking]
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              has a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the Wizarding World
              of Edinburgh tour.</p>
          /visitscotland:stops[1]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 8b215960-87aa-47ae-9c11-8a750be25ad8
          /visitscotland:stops[2]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: fb585bd7-188e-4430-a332-bf0fbc337d23
          /visitscotland:stops[3]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: ca56dfe6-f8c8-410f-aa63-ed513fc71385
          /visitscotland:stops[4]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 28abd074-5fc4-4ebc-a424-1d4f9e5cb0e6
        /edimburgo[3]:
          jcr:primaryType: visitscotland:Day
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: dabf67a9-1e6b-4dad-97a0-f826df53bf9e
          hippo:availability: [live]
          hippostd:state: published
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-10T13:28:39.550Z
          hippostdpubwf:lastModificationDate: 2020-07-03T13:57:49.398+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippostdpubwf:publicationDate: 2020-07-03T13:58:03.782+01:00
          hippotranslation:id: 533c98b2-c2cd-491f-929a-ea2c4a491bb2
          hippotranslation:locale: es
          visitscotland:title: DMS Stops Day
          visitscotland:transports: [car, train, walking]
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              has a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the Wizarding World
              of Edinburgh tour.</p>
          /visitscotland:stops[1]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 8b215960-87aa-47ae-9c11-8a750be25ad8
          /visitscotland:stops[2]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: fb585bd7-188e-4430-a332-bf0fbc337d23
          /visitscotland:stops[3]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: ca56dfe6-f8c8-410f-aa63-ed513fc71385
          /visitscotland:stops[4]:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 28abd074-5fc4-4ebc-a424-1d4f9e5cb0e6
