definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: ['../hst:defaults', '../visitscotland/hst:workspace']
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /visitscotland-catalog:
            jcr:primaryType: hst:containeritempackage
      /visitscotland:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default]
      /visitscotland-es:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-fr:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-de:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-nl:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-it:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /vs-default:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common, '../visitscotland/hst:workspace']
      /business-events:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /bsh:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
