definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: ['../hst:defaults', '../visitscotland/hst:workspace']
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
          /root:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/homepage
            hst:pagetitle: Home Page
            hst:refId: root
          /_any_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
          /pagenotfound:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:pagetitle: Not Found Page
            hst:refId: pagenotfound
          /widget:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/widget
            hst:relativecontentpath: navigation
            /_any_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/widget
              hst:relativecontentpath: ${parent}/${1}
          /destinations-maps:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: site/see-do
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/content
          /see-do:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: site/see-do
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/content
          /accommodation:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: site/see-do
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/content
          /plan-your-trip:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: site/see-do
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/content
          /trip-ideas:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: site/see-do
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/content
          /_default_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: site/${1}
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                'visitscotland:Listicle']
              hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                'hst:pages/listicle-page']
              hst:relativecontentpath: ${parent}/content
            /_default_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/${2}
              /_index_:
                jcr:primaryType: hst:sitemapitem
                hst:componentconfigurationid: hst:pages/pagenotfound
                hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                  'visitscotland:Listicle']
                hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                  'hst:pages/listicle-page']
                hst:relativecontentpath: ${parent}/content
              /_default_:
                jcr:primaryType: hst:sitemapitem
                hst:componentconfigurationid: hst:pages/pagenotfound
                hst:relativecontentpath: ${parent}/${3}
                /_index_:
                  jcr:primaryType: hst:sitemapitem
                  hst:componentconfigurationid: hst:pages/pagenotfound
                  hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                    'visitscotland:Listicle']
                  hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                    'hst:pages/listicle-page']
                  hst:relativecontentpath: ${parent}/content
                /_default_:
                  jcr:primaryType: hst:sitemapitem
                  hst:componentconfigurationid: hst:pages/pagenotfound
                  hst:relativecontentpath: ${parent}/${4}
                  /_index_:
                    jcr:primaryType: hst:sitemapitem
                    hst:componentconfigurationid: hst:pages/pagenotfound
                    hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                      'visitscotland:Listicle']
                    hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                      'hst:pages/listicle-page']
                    hst:relativecontentpath: ${parent}/content
                  /_default_:
                    jcr:primaryType: hst:sitemapitem
                    hst:componentconfigurationid: hst:pages/pagenotfound
                    hst:relativecontentpath: ${parent}/${4}
                    /_index_:
                      jcr:primaryType: hst:sitemapitem
                      hst:componentconfigurationid: hst:pages/pagenotfound
                      hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                        'visitscotland:Listicle']
                      hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                        'hst:pages/listicle-page']
                      hst:relativecontentpath: ${parent}/content
                    /_default_:
                      jcr:primaryType: hst:sitemapitem
                      hst:componentconfigurationid: hst:pages/pagenotfound
                      hst:relativecontentpath: ${parent}/${4}
                      /_index_:
                        jcr:primaryType: hst:sitemapitem
                        hst:componentconfigurationid: hst:pages/pagenotfound
                        hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                          'visitscotland:Listicle']
                        hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                          'hst:pages/listicle-page']
                        hst:relativecontentpath: ${parent}/content
          /dev-test:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: site/dev-test
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/content
              hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                'hst:pages/listicle-page']
              hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                'visitscotland:Listicle']
            /_default_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/pagenotfound
              hst:relativecontentpath: ${parent}/${1}
              /_index_:
                jcr:primaryType: hst:sitemapitem
                hst:componentconfigurationid: hst:pages/pagenotfound
                hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                  'visitscotland:Listicle']
                hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                  'hst:pages/listicle-page']
                hst:relativecontentpath: ${parent}/content
              /_default_:
                jcr:primaryType: hst:sitemapitem
                hst:componentconfigurationid: hst:pages/pagenotfound
                hst:relativecontentpath: ${parent}/${2}
                /_index_:
                  jcr:primaryType: hst:sitemapitem
                  hst:componentconfigurationid: hst:pages/pagenotfound
                  hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                    'visitscotland:Listicle']
                  hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                    'hst:pages/listicle-page']
                  hst:relativecontentpath: ${parent}/content
                /_default_:
                  jcr:primaryType: hst:sitemapitem
                  hst:componentconfigurationid: hst:pages/pagenotfound
                  hst:relativecontentpath: ${parent}/${3}
                  /_index_:
                    jcr:primaryType: hst:sitemapitem
                    hst:componentconfigurationid: hst:pages/pagenotfound
                    hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                      'visitscotland:Listicle']
                    hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                      'hst:pages/listicle-page']
                    hst:relativecontentpath: ${parent}/content
                  /_default_:
                    jcr:primaryType: hst:sitemapitem
                    hst:componentconfigurationid: hst:pages/pagenotfound
                    hst:relativecontentpath: ${parent}/${4}
                    /_index_:
                      jcr:primaryType: hst:sitemapitem
                      hst:componentconfigurationid: hst:pages/pagenotfound
                      hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                        'visitscotland:Listicle']
                      hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                        'hst:pages/listicle-page']
                      hst:relativecontentpath: ${parent}/content
                    /_default_:
                      jcr:primaryType: hst:sitemapitem
                      hst:componentconfigurationid: hst:pages/pagenotfound
                      hst:relativecontentpath: ${parent}/${5}
                      /_index_:
                        jcr:primaryType: hst:sitemapitem
                        hst:componentconfigurationid: hst:pages/pagenotfound
                        hst:componentconfigurationmappingnames: ['visitscotland:Itinerary',
                          'visitscotland:Listicle']
                        hst:componentconfigurationmappingvalues: ['hst:pages/itinerary-page',
                          'hst:pages/listicle-page']
                        hst:relativecontentpath: ${parent}/content
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/base-layout.ftl
          /base-top-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/base-top-menu.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/base-footer.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/pagenotfound-main.ftl
          /breadcrumb:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/breadcrumb.ftl
          /itinerary:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/itinerary-main.ftl
          /listicle:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/listicle-main.ftl
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /visitscotland-catalog:
            jcr:primaryType: hst:containeritempackage
      /visitscotland:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /backup:
        jcr:primaryType: hst:configuration
      /visitscotland-es:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common, '../common/hst:workspace']
      /visitscotland-fr:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common, '../common/hst:workspace']
      /visitscotland-de:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common, '../common/hst:workspace']
      /visitscotland-nl:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common, '../common/hst:workspace']
      /visitscotland-it:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common, '../common/hst:workspace']
