definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:defaultport: 8080
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:visitscotland/hst:sites/visitscotland
          hst:locale: en_GB
          /es-es:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:locale: es_ES
            hst:mountpoint: /hst:visitscotland/hst:sites/visitscotland-es
          /de-de:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:locale: de_DE
            hst:mountpoint: /hst:visitscotland/hst:sites/visitscotland-de
          /fr-fr:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:locale: fr_FR
            hst:mountpoint: /hst:visitscotland/hst:sites/visitscotland-fr
          /nl-nl:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:locale: nl_NL
            hst:mountpoint: /hst:visitscotland/hst:sites/visitscotland-nl
          /it-it:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:locale: it_IT
            hst:mountpoint: /hst:visitscotland/hst:sites/visitscotland-it
    /hst:hst/hst:hosts:
      hst:defaultcontextpath: /site
      hst:locale: en_GB
