/content/documents/www.visitscotland.com-nl/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c551e12e-5457-4974-8692-096a03cddf0d
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: nl
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: d8d65f84-985b-4a54-9b31-9ad4418f3915
    hippo:name: Home Page (NL)
    hippo:versionHistory: 254b04ad-f8a9-4c15-8215-029c27c52da1
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: 006d2533-7f39-41df-9eee-f5cc6a47253a
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T09:54:09.606+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: nl
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Default
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Welkom In Schotland
      visitscotland:theme: Standard
      visitscotland:title: Maak je klaar voor Schotland
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>We hopen, zodra het weer kan, iedereen ter wereld in ons prachtig land weer te mogen verwelkomen. Geniet tot die tijd van onze mooie foto's van Schotland en begin alvast voorzichtig met plannen. Schotland opent zijn deuren naar alle verwachtingen in de nazomer.</p>

          <p>Onze afgelegen&nbsp;heuvels, bergen, eilanden,&nbsp;uitgestrekte kust en andere adembenemende plekken vormen de ideale&nbsp;bestemming voor een ontspannen uitje. Ook onze bruisende steden zul je in de toekomst weer met een gerust hart kunnen bezoeken.</p>

          <p>Maak van Schotlands <a href="https://www.visitscotland.com/nl-nl/about/themed-years/coasts-waters/" title="jaar van kust en water">Jaar van Kust &amp; Water</a> gebruik, en plan vanaf de nazomer een romantische vakantie voor twee, een epische reis met vrienden of een welverdiende&nbsp;reünie met opa en oma aan de Schotse kust.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 3a0b261a-52ea-449a-b36a-4402b51e71f2
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T09:54:06.907+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: nl
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Default
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Welkom In Schotland
      visitscotland:theme: Standard
      visitscotland:title: Maak je klaar voor Schotland
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>We hopen, zodra het weer kan, iedereen ter wereld in ons prachtig land weer te mogen verwelkomen. Geniet tot die tijd van onze mooie foto's van Schotland en begin alvast voorzichtig met plannen. Schotland opent zijn deuren naar alle verwachtingen in de nazomer.</p>

          <p>Onze afgelegen&nbsp;heuvels, bergen, eilanden,&nbsp;uitgestrekte kust en andere adembenemende plekken vormen de ideale&nbsp;bestemming voor een ontspannen uitje. Ook onze bruisende steden zul je in de toekomst weer met een gerust hart kunnen bezoeken.</p>

          <p>Maak van Schotlands <a href="https://www.visitscotland.com/nl-nl/about/themed-years/coasts-waters/" title="jaar van kust en water">Jaar van Kust &amp; Water</a> gebruik, en plan vanaf de nazomer een romantische vakantie voor twee, een epische reis met vrienden of een welverdiende&nbsp;reünie met opa en oma aan de Schotse kust.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 4c26b503-04dc-4148-933f-9c056a529fdf
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T09:54:09.606+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2024-06-21T09:54:12.114+01:00
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: nl
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Default
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Welkom In Schotland
      visitscotland:theme: Standard
      visitscotland:title: Maak je klaar voor Schotland
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>We hopen, zodra het weer kan, iedereen ter wereld in ons prachtig land weer te mogen verwelkomen. Geniet tot die tijd van onze mooie foto's van Schotland en begin alvast voorzichtig met plannen. Schotland opent zijn deuren naar alle verwachtingen in de nazomer.</p>

          <p>Onze afgelegen&nbsp;heuvels, bergen, eilanden,&nbsp;uitgestrekte kust en andere adembenemende plekken vormen de ideale&nbsp;bestemming voor een ontspannen uitje. Ook onze bruisende steden zul je in de toekomst weer met een gerust hart kunnen bezoeken.</p>

          <p>Maak van Schotlands <a href="https://www.visitscotland.com/nl-nl/about/themed-years/coasts-waters/" title="jaar van kust en water">Jaar van Kust &amp; Water</a> gebruik, en plan vanaf de nazomer een romantische vakantie voor twee, een epische reis met vrienden of een welverdiende&nbsp;reünie met opa en oma aan de Schotse kust.</p>
  /site-search-results:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 12e4507d-459e-4c70-9810-715280573391
    hippo:name: search-results
    hippostd:foldertype: [new-translated-folder, new-page, new-module]
    hippotranslation:id: ff87714b-7240-4eab-b6bd-12b1ff545ee3
    hippotranslation:locale: nl
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: a55b881d-d812-4bb6-861e-3c36ba8e219a
      hippo:name: Search results (NL)
      hippo:versionHistory: ef99a4bb-a6b6-4388-8b5c-ce4c115e1a26
      /content[1]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:versionable']
        jcr:uuid: b242e90a-4ca1-46a8-ad7c-18a52be37a71
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:13.485Z
        hippostdpubwf:lastModificationDate: 2024-06-21T09:54:29.557+01:00
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: nl
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[2]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 6558aeed-430f-45b1-9f84-dbdbc50a0427
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:13.485Z
        hippostdpubwf:lastModificationDate: 2024-06-21T09:54:29.557+01:00
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2024-06-21T09:54:32.087+01:00
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: nl
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[3]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 9d582a2d-58c1-4f28-a3d7-ecda5746264e
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:13.485Z
        hippostdpubwf:lastModificationDate: 2024-06-21T09:54:26.799+01:00
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: nl
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
