/content/documents/www.visitscotland.com-nl/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c551e12e-5457-4974-8692-096a03cddf0d
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: nl
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: d8d65f84-985b-4a54-9b31-9ad4418f3915
    hippo:name: Home Page (NL)
    hippo:versionHistory: f2a8df7d-21b1-418b-b5de-dfd2b1cd0319
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: 006d2533-7f39-41df-9eee-f5cc6a47253a
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:34:40.955+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: nl
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Welkom In Schotland
      visitscotland:theme: Standard
      visitscotland:title: Maak je klaar voor Schotland
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>We hopen, zodra het weer kan, iedereen ter wereld in ons prachtig land weer te mogen verwelkomen. Geniet tot die tijd van onze mooie foto's van Schotland en begin alvast voorzichtig met plannen. Schotland opent zijn deuren naar alle verwachtingen in de nazomer.</p>

          <p>Onze afgelegen&nbsp;heuvels, bergen, eilanden,&nbsp;uitgestrekte kust en andere adembenemende plekken vormen de ideale&nbsp;bestemming voor een ontspannen uitje. Ook onze bruisende steden zul je in de toekomst weer met een gerust hart kunnen bezoeken.</p>

          <p>Maak van Schotlands <a href="https://www.visitscotland.com/nl-nl/about/themed-years/coasts-waters/" title="jaar van kust en water">Jaar van Kust &amp; Water</a> gebruik, en plan vanaf de nazomer een romantische vakantie voor twee, een epische reis met vrienden of een welverdiende&nbsp;reünie met opa en oma aan de Schotse kust.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 3a0b261a-52ea-449a-b36a-4402b51e71f2
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:34:41.054+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: nl
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Welkom In Schotland
      visitscotland:theme: Standard
      visitscotland:title: Maak je klaar voor Schotland
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>We hopen, zodra het weer kan, iedereen ter wereld in ons prachtig land weer te mogen verwelkomen. Geniet tot die tijd van onze mooie foto's van Schotland en begin alvast voorzichtig met plannen. Schotland opent zijn deuren naar alle verwachtingen in de nazomer.</p>

          <p>Onze afgelegen&nbsp;heuvels, bergen, eilanden,&nbsp;uitgestrekte kust en andere adembenemende plekken vormen de ideale&nbsp;bestemming voor een ontspannen uitje. Ook onze bruisende steden zul je in de toekomst weer met een gerust hart kunnen bezoeken.</p>

          <p>Maak van Schotlands <a href="https://www.visitscotland.com/nl-nl/about/themed-years/coasts-waters/" title="jaar van kust en water">Jaar van Kust &amp; Water</a> gebruik, en plan vanaf de nazomer een romantische vakantie voor twee, een epische reis met vrienden of een welverdiende&nbsp;reünie met opa en oma aan de Schotse kust.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 4c26b503-04dc-4148-933f-9c056a529fdf
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:34:40.955+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2021-06-29T17:34:51.548+01:00
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: nl
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Welkom In Schotland
      visitscotland:theme: Standard
      visitscotland:title: Maak je klaar voor Schotland
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>We hopen, zodra het weer kan, iedereen ter wereld in ons prachtig land weer te mogen verwelkomen. Geniet tot die tijd van onze mooie foto's van Schotland en begin alvast voorzichtig met plannen. Schotland opent zijn deuren naar alle verwachtingen in de nazomer.</p>

          <p>Onze afgelegen&nbsp;heuvels, bergen, eilanden,&nbsp;uitgestrekte kust en andere adembenemende plekken vormen de ideale&nbsp;bestemming voor een ontspannen uitje. Ook onze bruisende steden zul je in de toekomst weer met een gerust hart kunnen bezoeken.</p>

          <p>Maak van Schotlands <a href="https://www.visitscotland.com/nl-nl/about/themed-years/coasts-waters/" title="jaar van kust en water">Jaar van Kust &amp; Water</a> gebruik, en plan vanaf de nazomer een romantische vakantie voor twee, een epische reis met vrienden of een welverdiende&nbsp;reünie met opa en oma aan de Schotse kust.</p>
