/content/documents/www.visitscotland.com-es/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 0bf214e8-a36c-418b-ade2-f63b5056ddd9
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: es
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: c47956b1-d9b0-431e-bc85-57256be33c1f
    hippo:name: Home Page (ES)
    hippo:versionHistory: 22407aee-f9c2-4bb2-b683-1669aa4934ef
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: 45d82118-dfdd-42fd-af4b-4f7c3f2dfec6
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:29:06.254+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: es
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Bienvenido a Escocia
      visitscotland:theme: Standard
      visitscotland:title: Prepárate para Escocia
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Somos un país innovador, por lo que, si no puedes venir en persona, no te olvides de echar un vistazo a nuestra página web y a las redes sociales para&nbsp;descubrir una gran cantidad de contenido inspirador sobre Escocia. Esta es nuestra forma de hacerte sonreir en estos meses tan&nbsp;difíciles.</p>

          <p>Nuestro país, regiones, ciudades, pueblos y negocios son increíbles, y trabajaremos&nbsp;juntos&nbsp;para asegurarnos de que cuando sea seguro para todos,&nbsp;tu próximo viaje sea inolvidable.</p>

          <p>Mientras tanto, puedes consultar las directrices y consejos del Gobierno de Escocia en este <a href="https://www.visitscotland.com/es-es/about/practical-information/covid-19-recovery-phases/" title="" target="_blank">enlace</a>.</p>

          <p>Esperamos poder darte la bienvenida a Escocia muy pronto.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 79411fbe-a5af-409b-99d9-799d8af2967f
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:29:06.328+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: es
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Bienvenido a Escocia
      visitscotland:theme: Standard
      visitscotland:title: Prepárate para Escocia
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Somos un país innovador, por lo que, si no puedes venir en persona, no te olvides de echar un vistazo a nuestra página web y a las redes sociales para&nbsp;descubrir una gran cantidad de contenido inspirador sobre Escocia. Esta es nuestra forma de hacerte sonreir en estos meses tan&nbsp;difíciles.</p>

          <p>Nuestro país, regiones, ciudades, pueblos y negocios son increíbles, y trabajaremos&nbsp;juntos&nbsp;para asegurarnos de que cuando sea seguro para todos,&nbsp;tu próximo viaje sea inolvidable.</p>

          <p>Mientras tanto, puedes consultar las directrices y consejos del Gobierno de Escocia en este <a href="https://www.visitscotland.com/es-es/about/practical-information/covid-19-recovery-phases/" title="" target="_blank">enlace</a>.</p>

          <p>Esperamos poder darte la bienvenida a Escocia muy pronto.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 44c7eea2-f34d-4f4f-aa8b-91cfec40492e
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:29:06.254+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2021-06-29T17:35:42.657+01:00
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: es
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Bienvenido a Escocia
      visitscotland:theme: Standard
      visitscotland:title: Prepárate para Escocia
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Somos un país innovador, por lo que, si no puedes venir en persona, no te olvides de echar un vistazo a nuestra página web y a las redes sociales para&nbsp;descubrir una gran cantidad de contenido inspirador sobre Escocia. Esta es nuestra forma de hacerte sonreir en estos meses tan&nbsp;difíciles.</p>

          <p>Nuestro país, regiones, ciudades, pueblos y negocios son increíbles, y trabajaremos&nbsp;juntos&nbsp;para asegurarnos de que cuando sea seguro para todos,&nbsp;tu próximo viaje sea inolvidable.</p>

          <p>Mientras tanto, puedes consultar las directrices y consejos del Gobierno de Escocia en este <a href="https://www.visitscotland.com/es-es/about/practical-information/covid-19-recovery-phases/" title="" target="_blank">enlace</a>.</p>

          <p>Esperamos poder darte la bienvenida a Escocia muy pronto.</p>
