/content/documents/www.visitscotland.com-es/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 0bf214e8-a36c-418b-ade2-f63b5056ddd9
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: es
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: c47956b1-d9b0-431e-bc85-57256be33c1f
    hippo:name: Home Page (ES)
    hippo:versionHistory: 1626fe0a-1531-4840-8991-d337e6e2cb7d
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: 45d82118-dfdd-42fd-af4b-4f7c3f2dfec6
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-02-25T10:23:33.642Z
      hippostdpubwf:lastModifiedBy: editor
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: es
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Bienvenido a Escocia
      visitscotland:theme: Standard
      visitscotland:title: Prepárate para Escocia
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Somos un país innovador, por lo que, si no puedes venir en persona, no te olvides de echar un vistazo a nuestra página web y a las redes sociales para&nbsp;descubrir una gran cantidad de contenido inspirador sobre Escocia. Esta es nuestra forma de hacerte sonreir en estos meses tan&nbsp;difíciles.</p>

          <p>Nuestro país, regiones, ciudades, pueblos y negocios son increíbles, y trabajaremos&nbsp;juntos&nbsp;para asegurarnos de que cuando sea seguro para todos,&nbsp;tu próximo viaje sea inolvidable.</p>

          <p>Mientras tanto, puedes consultar las directrices y consejos del Gobierno de Escocia en este <a rel="noopener noreferrer" href="https://www.visitscotland.com/es-es/about/practical-information/covid-19-recovery-phases/" title="" target="_blank">enlace</a>.</p>

          <p>Esperamos poder darte la bienvenida a Escocia muy pronto.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 79411fbe-a5af-409b-99d9-799d8af2967f
      hippo:availability: []
      hippostd:holder: admin
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T11:29:24.959+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: es
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Bienvenido a Escocia
      visitscotland:theme: Standard
      visitscotland:title: Prepárate para Escocia
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Somos un país innovador, por lo que, si no puedes venir en persona, no te olvides de echar un vistazo a nuestra página web y a las redes sociales para&nbsp;descubrir una gran cantidad de contenido inspirador sobre Escocia. Esta es nuestra forma de hacerte sonreir en estos meses tan&nbsp;difíciles.</p>

          <p>Nuestro país, regiones, ciudades, pueblos y negocios son increíbles, y trabajaremos&nbsp;juntos&nbsp;para asegurarnos de que cuando sea seguro para todos,&nbsp;tu próximo viaje sea inolvidable.</p>

          <p>Mientras tanto, puedes consultar las directrices y consejos del Gobierno de Escocia en este <a rel="noopener noreferrer" href="https://www.visitscotland.com/es-es/about/practical-information/covid-19-recovery-phases/" title="" target="_blank">enlace</a>.</p>

          <p>Esperamos poder darte la bienvenida a Escocia muy pronto.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 44c7eea2-f34d-4f4f-aa8b-91cfec40492e
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-02-25T10:23:33.642Z
      hippostdpubwf:lastModifiedBy: editor
      hippostdpubwf:publicationDate: 2022-02-25T10:23:43.790Z
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: es
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Bienvenido a Escocia
      visitscotland:theme: Standard
      visitscotland:title: Prepárate para Escocia
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Somos un país innovador, por lo que, si no puedes venir en persona, no te olvides de echar un vistazo a nuestra página web y a las redes sociales para&nbsp;descubrir una gran cantidad de contenido inspirador sobre Escocia. Esta es nuestra forma de hacerte sonreir en estos meses tan&nbsp;difíciles.</p>

          <p>Nuestro país, regiones, ciudades, pueblos y negocios son increíbles, y trabajaremos&nbsp;juntos&nbsp;para asegurarnos de que cuando sea seguro para todos,&nbsp;tu próximo viaje sea inolvidable.</p>

          <p>Mientras tanto, puedes consultar las directrices y consejos del Gobierno de Escocia en este <a rel="noopener noreferrer" href="https://www.visitscotland.com/es-es/about/practical-information/covid-19-recovery-phases/" title="" target="_blank">enlace</a>.</p>

          <p>Esperamos poder darte la bienvenida a Escocia muy pronto.</p>
  /site-search-results:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 0e6bd01a-697c-4e5e-b3bd-d4539600c641
    hippo:name: search-results
    hippostd:foldertype: [new-translated-folder, new-page, new-module]
    hippotranslation:id: ff87714b-7240-4eab-b6bd-12b1ff545ee3
    hippotranslation:locale: es
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: cfcb4e5e-3962-45b7-a22e-170a66c505fa
      hippo:name: Search results (ES)
      hippo:versionHistory: c6b8d3ec-91b1-4117-a126-add22aaab9dc
      /content[1]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:versionable']
        jcr:uuid: 7f227d36-97da-4110-bc3b-8c5632da3554
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:11.280Z
        hippostdpubwf:lastModificationDate: 2022-03-10T15:17:11.160Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: es
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[2]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 59677c7f-c8c2-4d31-98ec-6ecffca866dd
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:11.280Z
        hippostdpubwf:lastModificationDate: 2022-03-10T15:17:11.160Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2022-03-10T17:31:28.833Z
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: es
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
