definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost/local:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhost
      /businessevents:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          jcr:mixinTypes: ['visitscotland:hosts']
          hst:homepage: root
          hst:locale: en_GB
          hst:mountpoint: /hst:visitscotland/hst:sites/business-events
          hst:pagemodelapi: resourceapi
          hst:responseheaders: ['Access-Control-Allow-Origin: *']
          visitscotland:cmsProperties: cms.local.config
          visitscotland:siteProperties: businessevents.local.config
          /api:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:ismapped: false
            hst:namedpipeline: JaxrsRestPlainPipeline
            hst:types: [rest]
      /bsh:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          jcr:mixinTypes: ['visitscotland:hosts']
          hst:homepage: root
          hst:locale: en_GB
          hst:mountpoint: /hst:visitscotland/hst:sites/bsh
          hst:pagemodelapi: resourceapi
          hst:responseheaders: ['Access-Control-Allow-Origin: *']
          visitscotland:cmsProperties: cms.local.config
          visitscotland:siteProperties: bsh.local.config
          /api:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:ismapped: false
            hst:namedpipeline: JaxrsRestPlainPipeline
            hst:types: [rest]
