definitions:
  config:
    /hippo:namespaces/visitscotland/default:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: d86fb097-f73c-4766-be58-db34f543c729
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: f7f727cc-2ff9-463a-a7a7-b8209460e712
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:node: true
          hipposysedit:supertype: ['hippogallery:imageset', 'hippogallery:relaxed']
          hipposysedit:uri: http://www.visitscotland.com/visitscotland/nt/1.0
          /filename:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:filename
            hipposysedit:type: String
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:description
            hipposysedit:type: String
          /thumbnail:
            jcr:primaryType: hipposysedit:field
            hipposysedit:autocreated: true
            hipposysedit:mandatory: true
            hipposysedit:path: hippogallery:thumbnail
            hipposysedit:primary: true
            hipposysedit:type: hippogallery:image
          /original:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:original
            hipposysedit:type: hippogallery:image
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: visitscotland:default
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: e5fd9608-1463-49df-885b-1185097e0491
          /hippogallery:thumbnail:
            jcr:primaryType: hippogallery:image
            jcr:data:
              type: binary
              resource: /namespaces/visitscotland/default/prototypes/prototype/thumbnail/thumbnail.jpg
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
            jcr:encoding: UTF-8
            hippogallery:height: 94
            hippogallery:width: 94
          /hippogallery:original:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 0
            hippogallery:width: 0
            jcr:data:
              type: binary
              resource: /namespaces/visitscotland/default/prototypes/prototype/original/original.gif
            jcr:lastModified: 1970-01-01T00:00:00Z
            jcr:mimeType: image/gif
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [model.compareTo, wicket.model, engine]
          frontend:services: [wicket.id]
          mode: edit
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /filename:
            jcr:primaryType: frontend:plugin
            caption: file name
            field: filename
            plugin.class: org.hippoecm.frontend.plugins.gallery.editor.FileNameDisplayPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /thumbnail:
            jcr:primaryType: frontend:plugin
            caption: thumbnail
            field: thumbnail
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /original:
            jcr:primaryType: frontend:plugin
            caption: original
            field: original
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
