definitions:
  config:
    /hippo:namespaces/visitscotland/ProductsSearch:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: df968967-65df-4ec7-bec0-4575309b9db1
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 2fc5db78-2ea0-43cd-b7d9-e9d680b4895a
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: cfb8d677-9617-4a29-8320-98ca2be788bb
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.visitscotland.com/visitscotland/nt/1.0
          /location:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:location
            hipposysedit:primary: false
            hipposysedit:type: DynamicDropdown
            hipposysedit:validators: [required]
          /producttype:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:productType
            hipposysedit:primary: false
            hipposysedit:type: DynamicDropdown
            hipposysedit:validators: [required]
          /officialrating:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:officialrating
            hipposysedit:primary: false
            hipposysedit:type: String
          /distance:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:distance
            hipposysedit:primary: false
            hipposysedit:type: Double
            hipposysedit:validators: [required]
          /offers:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:offers
            hipposysedit:primary: false
            hipposysedit:type: Boolean
          /free:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:free
            hipposysedit:primary: false
            hipposysedit:type: Boolean
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: visitscotland:ProductsSearch
          visitscotland:location: Scotland
          visitscotland:dmsCategories: []
          visitscotland:dmsAwards: []
          visitscotland:dmsFacilities: []
          visitscotland:officialrating: []
          visitscotland:productType: ''
          visitscotland:distance: 10.0
          visitscotland:free: false
          visitscotland:offers: false
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /productType:
            jcr:primaryType: frontend:plugin
            caption: Product Type
            field: producttype
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              orientation: vertical
              source: /content/documents/administration/options/product-search
          /dmscategorycselector:
            jcr:primaryType: frontend:plugin
            caption: DMS category
            engine: ${engine}
            dms.productype: visitscotland:productType
            example.external.docs.field.name: visitscotland:dmsCategories
            external.document.service.facade: com.visitscotland.brxm.components.DMSCategoryPicker
            initial.search.enabled: true
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.ExternalDocumentFieldSelectorPlugin
            selection.mode: multiple
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            page.size: 8
            icon.style: 'display: none;'
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /location:
            jcr:primaryType: frontend:plugin
            caption: Location
            field: location
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              valuelistProvider: service.locationlist.psr
          /dmsfacilitycselector:
            jcr:primaryType: frontend:plugin
            caption: DMS facility
            engine: ${engine}
            dms.productype: visitscotland:productType
            example.external.docs.field.name: visitscotland:dmsFacilities
            external.document.service.facade: com.visitscotland.brxm.components.DMSFacilityPicker
            initial.search.enabled: true
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.ExternalDocumentFieldSelectorPlugin
            selection.mode: multiple
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            page.size: 8
            icon.style: 'display: none;'
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /dmsawardcselector:
            jcr:primaryType: frontend:plugin
            caption: DMS awards
            engine: ${engine}
            dms.productype: visitscotland:productType
            example.external.docs.field.name: visitscotland:dmsAwards
            external.document.service.facade: com.visitscotland.brxm.components.DMSAwardPicker
            initial.search.enabled: true
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.ExternalDocumentFieldSelectorPlugin
            selection.mode: multiple
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            page.size: 8
            icon.style: 'display: none;'
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /officialrating:
            jcr:primaryType: frontend:plugin
            caption: Official rating
            field: officialrating
            multiselect.type: checkboxes
            palette.alloworder: false
            palette.maxrows: '10'
            plugin.class: org.onehippo.forge.selection.frontend.plugin.DynamicMultiSelectPlugin
            selectlist.maxrows: '10'
            valuelist.provider: service.valuelist.default
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/administration/options/official-rating
          /free:
            jcr:primaryType: frontend:plugin
            caption: Free
            field: free
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /offers:
            jcr:primaryType: frontend:plugin
            caption: Only show results with offers
            field: offers
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /distance:
            jcr:primaryType: frontend:plugin
            caption: Distance
            field: distance
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
