definitions:
  config:
    /hippo:namespaces/visitscotland/ProductSearch:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 8114571d-6db3-4612-8bc6-ad20710613c3
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 69883bfa-8412-4b52-ac9d-64f85ee53a5c
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: c1ce6fa3-4608-4515-86aa-e976d02f56c9
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.visitscotland.com/visitscotland/nt/1.0
          /productType:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:productType
            hipposysedit:primary: false
            hipposysedit:type: StaticDropdown
          /location:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:location
            hipposysedit:primary: false
            hipposysedit:type: DynamicDropdown
          /dmsCategories:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:dmsCategories
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: visitscotland:ProductSearch
          visitscotland:location: ''
          visitscotland:dmsCategories: ''
          visitscotland:productType: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /location:
            jcr:primaryType: frontend:plugin
            caption: Location
            field: location
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              valuelistProvider: service.locationlist.default
          /dmscategorycselector:
            jcr:primaryType: frontend:plugin
            caption: DMS category
            engine: ${engine}
            example.external.docs.field.name: visitscotland:dmsCategories
            productype.field.name: visitscotland:productType
            external.document.service.facade: visitscotland.components.DMSCategoryPicker
            initial.search.enabled: true
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.ExternalDocumentFieldSelectorPlugin
            selection.mode: multiple
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            page.size: 10
            icon.style: 'display: none;'
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /productType:
            jcr:primaryType: frontend:plugin
            caption: Product type
            field: productType
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
