definitions:
  config:
    /hippo:namespaces/visitscotland/TrainingEventBSH:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: bb2d7355-f1ca-4e03-a072-971c21a6f62a
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: f44c3de8-b139-4d1c-a122-5bb642155769
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: f31d98d6-14b4-4573-86a3-0f61370d2ac4
          hipposysedit:node: true
          hipposysedit:supertype: ['visitscotland:EventBSH', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.visitscotland.com/visitscotland/nt/1.0
          /sectors:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:sectors
            hipposysedit:primary: false
            hipposysedit:type: String
          /topics:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:topics
            hipposysedit:primary: false
            hipposysedit:type: String
          /region:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:region
            hipposysedit:primary: false
            hipposysedit:type: DynamicDropdown
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: visitscotland:TrainingEventBSH
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          visitscotland:online: false
          visitscotland:endTime: ''
          visitscotland:venue: ''
          visitscotland:organiser: ''
          visitscotland:startTime: ''
          visitscotland:endDate: 0001-01-01T12:00:00Z
          visitscotland:title: ''
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 7b00476b-03c3-4fd8-95d5-e6d28e477bbf
          hippostdpubwf:lastModificationDate: 2025-01-14T14:46:07.421Z
          hippostdpubwf:creationDate: 2025-01-14T14:46:07.421Z
          visitscotland:sectors: []
          visitscotland:topics: []
          visitscotland:region: ''
          /visitscotland:summary:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
          /visitscotland:ctaLink:
            jcr:primaryType: visitscotland:ExternalLink
            visitscotland:label: ''
            visitscotland:link: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            caption: Event Title
            field: title
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /summary:
            jcr:primaryType: frontend:plugin
            caption: Event Summary
            field: summary
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              ckeditor.config.appended.json: "{   extraPlugins: 'wordcount',   wordcount:\
                \ { \tcountSpacesAsChars: true,     showCharCount: true ,maxCharCount:350\
                \   }  }"
              ckeditor.config.overlayed.json: '{disallowedContent: ''p[align]'', toolbarGroups:
                [{ name: ''basicstyles''},{ name: ''links'' },{name:''insert''},{name:''clipboard''},{name:''tools''},{name:''undo''}]
                , removeButtons: ''PickImage,Youtube,Table,Bold,Underline,Strike,Subscript,Superscript''}'
          /ctaLink:
            jcr:primaryType: frontend:plugin
            caption: Event Link
            field: ctaLink
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /venue:
            jcr:primaryType: frontend:plugin
            caption: Venue/Location
            field: venue
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /organiser:
            jcr:primaryType: frontend:plugin
            caption: Organiser
            field: organiser
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /startDate:
            jcr:primaryType: frontend:plugin
            caption: Start Date
            field: startDate
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /endDate:
            jcr:primaryType: frontend:plugin
            caption: End Date
            field: endDate
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /startTime:
            jcr:primaryType: frontend:plugin
            caption: Start Time
            field: startTime
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /endTime:
            jcr:primaryType: frontend:plugin
            caption: End Time
            field: endTime
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /online:
            jcr:primaryType: frontend:plugin
            caption: Online
            field: online
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /region:
            jcr:primaryType: frontend:plugin
            caption: Region
            field: region
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              orientation: vertical
              source: /content/documents/administration/options/business-support-hub/regions
          /sectors:
            jcr:primaryType: frontend:plugin
            caption: sectors
            field: sectors
            multiselect.type: checkboxes
            palette.alloworder: false
            palette.maxrows: '10'
            plugin.class: org.onehippo.forge.selection.frontend.plugin.DynamicMultiSelectPlugin
            selectlist.maxrows: '10'
            valuelist.provider: service.valuelist.default
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/administration/options/business-support-hub/sector
          /price:
            jcr:primaryType: frontend:plugin
            caption: Price
            field: price
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /topics:
            jcr:primaryType: frontend:plugin
            caption: topics
            field: topics
            multiselect.type: checkboxes
            palette.alloworder: false
            palette.maxrows: '10'
            plugin.class: org.onehippo.forge.selection.frontend.plugin.DynamicMultiSelectPlugin
            selectlist.maxrows: '10'
            valuelist.provider: service.valuelist.default
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/administration/options/business-support-hub/topics---training-events
