/content/documents/administration/configuration:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['mix:versionable']
  jcr:uuid: d0615981-33e0-465c-be85-c8e21f90360d
  hippostd:foldertype: [new-untranslated-folder-resource-bundle, new-resource-bundle]
