/content/documents/administration/configuration:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['mix:versionable']
  jcr:uuid: 9140b45a-c9de-4022-b066-0b57f46110d9
  hippostd:foldertype: [new-resource-bundle, new-untranslated-folder]
