/content/documents/www.visitscotland.com-de/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 566ee841-076e-4d28-86bf-782ec8b201f2
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: de
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 40fb5852-bb0c-4327-b80f-5b64a80b6a93
    hippo:name: Home Page (DE)
    hippo:versionHistory: c1e25e5b-a19a-4d99-a2eb-9200b684392f
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: b4f3f467-c2ca-4020-88e6-188e1634d89f
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-02-25T10:22:57.476Z
      hippostdpubwf:lastModifiedBy: editor
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: de
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Bereiten Sie sich auf Schottland vor
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Wir werden unsere Webseite und Social-Media-Kanäle regelmäßig mit den neuesten Informationen aktualisieren. Sehen Sie dort nach, um mehr Details und natürlich jede Menge inspirierender und wunderschöner Inhalte zum Thema Schottland zu erhalten. Solange Sie uns nicht persönlich besuchen können, möchten wir Ihnen damit weiterhin ein Lächeln ins Gesicht zaubern.</p>

          <p>Unser Land, unsere Regionen, Städte, Orte und Unternehmen sind großartig und wir werden alle zusammenarbeiten, um sicherzustellen, dass Ihre nächste Reise nach Schottland Ihnen lange in Erinnerung bleiben wird, sobald sicheres Reisen wieder möglich ist.</p>

          <p>Für den Moment können Sie sich hier über die <a href="https://www.visitscotland.com/de-de/about/practical-information/covid-19-recovery-phases/" title="Covid 19 Recovery Phases">Hinweise der schottischen Regierung zur aktuellen Phase der COVID-19-Maßnahmen</a> informieren.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 3ae50683-3b00-456b-b6fa-c6bb8b51aa81
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostd:transferable: false
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-06-21T11:29:19.794+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: de
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Bereiten Sie sich auf Schottland vor
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Wir werden unsere Webseite und Social-Media-Kanäle regelmäßig mit den neuesten Informationen aktualisieren. Sehen Sie dort nach, um mehr Details und natürlich jede Menge inspirierender und wunderschöner Inhalte zum Thema Schottland zu erhalten. Solange Sie uns nicht persönlich besuchen können, möchten wir Ihnen damit weiterhin ein Lächeln ins Gesicht zaubern.</p>

          <p>Unser Land, unsere Regionen, Städte, Orte und Unternehmen sind großartig und wir werden alle zusammenarbeiten, um sicherzustellen, dass Ihre nächste Reise nach Schottland Ihnen lange in Erinnerung bleiben wird, sobald sicheres Reisen wieder möglich ist.</p>

          <p>Für den Moment können Sie sich hier über die <a href="https://www.visitscotland.com/de-de/about/practical-information/covid-19-recovery-phases/" title="Covid 19 Recovery Phases">Hinweise der schottischen Regierung zur aktuellen Phase der COVID-19-Maßnahmen</a> informieren.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a440164e-2e17-4ac3-b466-1a135072ecb9
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-02-25T10:22:57.476Z
      hippostdpubwf:lastModifiedBy: editor
      hippostdpubwf:publicationDate: 2022-02-25T10:23:14.416Z
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: de
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Bereiten Sie sich auf Schottland vor
      visitscotland:translation: ''
      visitscotland:translationFlag: false
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Wir werden unsere Webseite und Social-Media-Kanäle regelmäßig mit den neuesten Informationen aktualisieren. Sehen Sie dort nach, um mehr Details und natürlich jede Menge inspirierender und wunderschöner Inhalte zum Thema Schottland zu erhalten. Solange Sie uns nicht persönlich besuchen können, möchten wir Ihnen damit weiterhin ein Lächeln ins Gesicht zaubern.</p>

          <p>Unser Land, unsere Regionen, Städte, Orte und Unternehmen sind großartig und wir werden alle zusammenarbeiten, um sicherzustellen, dass Ihre nächste Reise nach Schottland Ihnen lange in Erinnerung bleiben wird, sobald sicheres Reisen wieder möglich ist.</p>

          <p>Für den Moment können Sie sich hier über die <a href="https://www.visitscotland.com/de-de/about/practical-information/covid-19-recovery-phases/" title="Covid 19 Recovery Phases">Hinweise der schottischen Regierung zur aktuellen Phase der COVID-19-Maßnahmen</a> informieren.</p>
  /site-search-results:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: b9d181ca-ef46-4a28-a585-b86831d682f3
    hippo:name: search-results
    hippostd:foldertype: [new-translated-folder, new-page, new-module]
    hippotranslation:id: ff87714b-7240-4eab-b6bd-12b1ff545ee3
    hippotranslation:locale: de
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: 91b928ce-9e32-421c-bdec-ed52f9c5dd30
      hippo:name: Search results (DE)
      hippo:versionHistory: d7e200d8-2cab-49a2-8f5c-1f5641f26fa3
      /content[1]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:versionable']
        jcr:uuid: 59ba04dd-59a8-4696-bf91-ababad007bf7
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:10.823Z
        hippostdpubwf:lastModificationDate: 2022-03-10T15:17:10.737Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: de
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[2]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 6c3fd686-488d-4190-befa-149ca325cf48
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T15:17:10.823Z
        hippostdpubwf:lastModificationDate: 2022-03-10T15:17:10.737Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2022-03-10T17:31:19.080Z
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: de
        visitscotland:breadcrumb: ''
        visitscotland:diff: ''
        visitscotland:hideNewsletter: true
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        visitscotland:translationFlag: true
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
