/content/documents/www.visitscotland.com-de/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 566ee841-076e-4d28-86bf-782ec8b201f2
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: de
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 40fb5852-bb0c-4327-b80f-5b64a80b6a93
    hippo:name: Home Page (DE)
    hippo:versionHistory: 9e37e403-c34f-4289-88c8-1c48676c5865
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: b4f3f467-c2ca-4020-88e6-188e1634d89f
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:29:54.331+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: de
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Bereiten Sie sich auf Schottland vor
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Wir werden unsere Webseite und Social-Media-Kanäle regelmäßig mit den neuesten Informationen aktualisieren. Sehen Sie dort nach, um mehr Details und natürlich jede Menge inspirierender und wunderschöner Inhalte zum Thema Schottland zu erhalten. Solange Sie uns nicht persönlich besuchen können, möchten wir Ihnen damit weiterhin ein Lächeln ins Gesicht zaubern.</p>

          <p>Unser Land, unsere Regionen, Städte, Orte und Unternehmen sind großartig und wir werden alle zusammenarbeiten, um sicherzustellen, dass Ihre nächste Reise nach Schottland Ihnen lange in Erinnerung bleiben wird, sobald sicheres Reisen wieder möglich ist.</p>

          <p>Für den Moment können Sie sich hier über die <a href="https://www.visitscotland.com/de-de/about/practical-information/covid-19-recovery-phases/" title="Covid 19 Recovery Phases">Hinweise der schottischen Regierung zur aktuellen Phase der COVID-19-Maßnahmen</a> informieren.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 3ae50683-3b00-456b-b6fa-c6bb8b51aa81
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:29:54.380+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: de
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Bereiten Sie sich auf Schottland vor
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Wir werden unsere Webseite und Social-Media-Kanäle regelmäßig mit den neuesten Informationen aktualisieren. Sehen Sie dort nach, um mehr Details und natürlich jede Menge inspirierender und wunderschöner Inhalte zum Thema Schottland zu erhalten. Solange Sie uns nicht persönlich besuchen können, möchten wir Ihnen damit weiterhin ein Lächeln ins Gesicht zaubern.</p>

          <p>Unser Land, unsere Regionen, Städte, Orte und Unternehmen sind großartig und wir werden alle zusammenarbeiten, um sicherzustellen, dass Ihre nächste Reise nach Schottland Ihnen lange in Erinnerung bleiben wird, sobald sicheres Reisen wieder möglich ist.</p>

          <p>Für den Moment können Sie sich hier über die <a href="https://www.visitscotland.com/de-de/about/practical-information/covid-19-recovery-phases/" title="Covid 19 Recovery Phases">Hinweise der schottischen Regierung zur aktuellen Phase der COVID-19-Maßnahmen</a> informieren.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a440164e-2e17-4ac3-b466-1a135072ecb9
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2021-06-29T17:29:54.331+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2021-06-29T17:35:46.198+01:00
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: de
      visitscotland:breadcrumb: ''
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Standard
      visitscotland:title: Bereiten Sie sich auf Schottland vor
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4cdd0883-80e6-4f4f-9fa1-4feec593a22e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Wir werden unsere Webseite und Social-Media-Kanäle regelmäßig mit den neuesten Informationen aktualisieren. Sehen Sie dort nach, um mehr Details und natürlich jede Menge inspirierender und wunderschöner Inhalte zum Thema Schottland zu erhalten. Solange Sie uns nicht persönlich besuchen können, möchten wir Ihnen damit weiterhin ein Lächeln ins Gesicht zaubern.</p>

          <p>Unser Land, unsere Regionen, Städte, Orte und Unternehmen sind großartig und wir werden alle zusammenarbeiten, um sicherzustellen, dass Ihre nächste Reise nach Schottland Ihnen lange in Erinnerung bleiben wird, sobald sicheres Reisen wieder möglich ist.</p>

          <p>Für den Moment können Sie sich hier über die <a href="https://www.visitscotland.com/de-de/about/practical-information/covid-19-recovery-phases/" title="Covid 19 Recovery Phases">Hinweise der schottischen Regierung zur aktuellen Phase der COVID-19-Maßnahmen</a> informieren.</p>
