/content/gallery/business-events/default:
  jcr:primaryType: hippogallery:stdImageGallery
  jcr:mixinTypes: ['mix:versionable']
  jcr:uuid: 55630377-2bbb-48ab-bb7d-b2ec2d8bbcd0
  hippostd:foldertype: [new-visitscotland-Image-folder]
  hippostd:gallerytype: ['visitscotland:Image']
