/content/documents/www.visitscotland.com-nl/site:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 975451b2-b2f1-41da-9713-84e5438ee74b
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: nl
  /dev-test:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
    jcr:uuid: a661e97c-bd6f-4563-9e4a-f18fb627e728
    hippostd:foldertype: [new-translated-folder, new-document]
    hippotranslation:id: 0ff458fa-cab8-47ba-9862-d8a0b7a1bacf
    hippotranslation:locale: nl
    /itinerary:
      jcr:primaryType: hippostd:folder
      jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
      jcr:uuid: c06125e4-4f99-4700-b434-d24c98a98a93
      hippostd:foldertype: [new-translated-folder, new-document]
      hippotranslation:id: 50c3b9d8-4fd6-460c-a3a6-cea7c7c00f01
      hippotranslation:locale: nl
      /content:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
        jcr:uuid: a1eb10fd-e50c-45ff-9764-f0d5dd4cfc1d
        hippo:name: Hippo Itinerary
        hippo:versionHistory: da04e080-f2b4-44b8-800b-7b3dc5fbd769
        /content[1]:
          jcr:primaryType: visitscotland:Itinerary
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: 373c266e-9815-4045-9654-d5807547738a
          hippo:availability: [preview]
          hippostd:state: unpublished
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
          hippostdpubwf:lastModificationDate: 2020-07-03T14:03:24.532+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippotranslation:id: 56cf92c8-5887-4146-ad53-eaa062f4e07a
          hippotranslation:locale: nl
          visitscotland:areas: [east, north]
          visitscotland:breadcrumb: Hola
          visitscotland:distance: 10.4
          visitscotland:finish: Ocean point
          visitscotland:highlights: "Glenfinnan Viaduct \r\nJacobite Steam Train\r\
            \nGlen Etive\r\nThe Elephant House"
          visitscotland:popular: false
          visitscotland:seoDescription: It was in Scotland's capital city that JK
            Rowling started to plot the adventures of Harry and his friends. With
            cobbled streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:seoNoIndex: false
          visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
          visitscotland:start: Tenerife
          visitscotland:summary: ''
          visitscotland:teaser: It was in Scotland's capital city that JK Rowling
            started to plot the adventures of Harry and his friends. With cobbled
            streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\
            \nGlen Etive\r\n\r\nThe Elephant House"
          visitscotland:theme: whisky
          visitscotland:title: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
          visitscotland:transport: [boat]
          visitscotland:transports: [car, train]
          /visitscotland:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              have a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
              World of Edinburgh</a> tour.</p>
          /visitscotland:ProductsSearch:
            jcr:primaryType: visitscotland:ProductsSearch
            visitscotland:distance: 0
            visitscotland:dmsCategories: [guesthouse, yurts, touringpark, hostel]
            visitscotland:dmscategories: ''
            visitscotland:location: ''
            visitscotland:producttype: ''
        /content[2]:
          jcr:primaryType: visitscotland:Itinerary
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 4a93a639-a44a-4715-a4bf-19202bd9c6f7
          hippo:availability: []
          hippostd:state: draft
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
          hippostdpubwf:lastModificationDate: 2020-07-03T14:03:28.975+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippotranslation:id: 56cf92c8-5887-4146-ad53-eaa062f4e07a
          hippotranslation:locale: nl
          visitscotland:areas: [east, north]
          visitscotland:breadcrumb: Hola
          visitscotland:distance: 10.4
          visitscotland:finish: Ocean point
          visitscotland:highlights: "Glenfinnan Viaduct \r\nJacobite Steam Train\r\
            \nGlen Etive\r\nThe Elephant House"
          visitscotland:popular: false
          visitscotland:seoDescription: It was in Scotland's capital city that JK
            Rowling started to plot the adventures of Harry and his friends. With
            cobbled streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:seoNoIndex: false
          visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
          visitscotland:start: Tenerife
          visitscotland:summary: ''
          visitscotland:teaser: It was in Scotland's capital city that JK Rowling
            started to plot the adventures of Harry and his friends. With cobbled
            streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\
            \nGlen Etive\r\n\r\nThe Elephant House"
          visitscotland:theme: whisky
          visitscotland:title: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
          visitscotland:transport: [boat]
          visitscotland:transports: [car, train]
          /visitscotland:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              have a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
              World of Edinburgh</a> tour.</p>
          /visitscotland:ProductsSearch:
            jcr:primaryType: visitscotland:ProductsSearch
            visitscotland:distance: 0
            visitscotland:dmsCategories: [guesthouse, yurts, touringpark, hostel]
            visitscotland:dmscategories: ''
            visitscotland:location: ''
            visitscotland:producttype: ''
        /content[3]:
          jcr:primaryType: visitscotland:Itinerary
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: f04f072b-2289-4414-9ab3-3dce5a5c74b0
          hippo:availability: [live]
          hippostd:state: published
          hippostdpubwf:createdBy: admin
          hippostdpubwf:creationDate: 2019-12-06T12:48:04.149Z
          hippostdpubwf:lastModificationDate: 2020-07-03T14:03:24.532+01:00
          hippostdpubwf:lastModifiedBy: admin
          hippostdpubwf:publicationDate: 2020-07-03T14:08:02.799+01:00
          hippotranslation:id: 56cf92c8-5887-4146-ad53-eaa062f4e07a
          hippotranslation:locale: nl
          visitscotland:areas: [east, north]
          visitscotland:breadcrumb: Hola
          visitscotland:distance: 10.4
          visitscotland:finish: Ocean point
          visitscotland:highlights: "Glenfinnan Viaduct \r\nJacobite Steam Train\r\
            \nGlen Etive\r\nThe Elephant House"
          visitscotland:popular: false
          visitscotland:seoDescription: It was in Scotland's capital city that JK
            Rowling started to plot the adventures of Harry and his friends. With
            cobbled streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:seoNoIndex: false
          visitscotland:seoTitle: Iconic Harry Potter Film Locations - An Itinerary
          visitscotland:start: Tenerife
          visitscotland:summary: ''
          visitscotland:teaser: It was in Scotland's capital city that JK Rowling
            started to plot the adventures of Harry and his friends. With cobbled
            streets, winding alleys and medieval architecture, the city certainly
            have a few things in common with the settings from the books and films.
          visitscotland:text: "Glenfinnan Viaduct\r\n\r\nJacobite Steam Train\r\n\r\
            \nGlen Etive\r\n\r\nThe Elephant House"
          visitscotland:theme: whisky
          visitscotland:title: HARRY POTTER FILM AND BOOK LOCATIONS ITINERARY
          visitscotland:transport: [boat]
          visitscotland:transports: [car, train]
          /visitscotland:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: 8d4f5036-64ca-4e5d-aa89-b348ae38b081
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /visitscotland:introduction:
            jcr:primaryType: hippostd:html
            hippostd:content: <p>It was in Scotland's capital city that JK Rowling
              started to plot the adventures of Harry and his friends. With cobbled
              streets, winding alleys and medieval architecture, the city certainly
              have a few things in common with the settings from the books and films.
              She wrote the early chapters in various cafés around the city's Old
              Town, before coming back to finish off the series from a peaceful suite
              in The Balmoral Hotel. It is also said that Hogwarts School was styled
              on Edinburgh’s Fettes College, a private school on the outskirts of
              Edinburgh’s west end new town. You could also try the <a href="https://www.visitscotland.com/info/tours/wizarding-world-of-edinburgh-03e61189">Wizarding
              World of Edinburgh</a> tour.</p>
          /visitscotland:ProductsSearch:
            jcr:primaryType: visitscotland:ProductsSearch
            visitscotland:distance: 0
            visitscotland:dmsCategories: [guesthouse, yurts, touringpark, hostel]
            visitscotland:dmscategories: ''
            visitscotland:location: ''
            visitscotland:producttype: ''
