/content/documents/business-events/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: e8d415ec-a08a-478c-bb98-2605a2854e47
  hippostd:foldertype: [new-be-folder, new-be-page, new-be-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: en
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 353aacad-a093-43af-ae54-90fe64d2b38e
    hippo:name: content
    hippo:versionHistory: d5653585-e6f2-474c-aac7-38117609acc1
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:versionable']
      jcr:uuid: 3aead015-e44c-413e-a0a7-dd18645e21d0
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-01-18T12:31:21.663Z
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: f1a75f0d-60a4-49b9-b879-5d143c70353e
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Hidden
      visitscotland:seoDescription: Welcome to VisitScotland Business Events. Your
        partners in Scotland for conferences, conventions, meetings, incentives and
        more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: Welcome to Business Events Scotland
      visitscotland:teaser: Welcome to VisitScotland Business Events. Your partners
        in Scotland for conferences, conventions, meetings, incentives and more!
      visitscotland:theme: Top-Level
      visitscotland:title: Welcome to Business Events Scotland
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>For years Scotland has welcomed the world's greatest thinkers, pioneers, innovators and leaders to the many international congresses, conferences and meetings we host. Scotland is an incredible destination for business events. Our world leading academia, research institutes, industries and innovation centres thrive on ideas, new challenges and the inspiration we can give and draw from delegates to our country.</p>

          <p>In Scotland we believe business events are a catalyst for social and economic transformation; they are a driver to tackle climate change; they are a voice for human rights; they are a leader in the global <a href="https://businessevents.visitscotland.com/why-scotland/journey-to-change/" title="Journey to change">Journey to Change</a>.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 0d729ccc-abf3-4195-a8be-5e9027379f9b
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-01-18T12:29:51.371Z
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: f1a75f0d-60a4-49b9-b879-5d143c70353e
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Hidden
      visitscotland:seoDescription: Welcome to VisitScotland Business Events. Your
        partners in Scotland for conferences, conventions, meetings, incentives and
        more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: Welcome to Business Events Scotland
      visitscotland:teaser: Welcome to VisitScotland Business Events. Your partners
        in Scotland for conferences, conventions, meetings, incentives and more!
      visitscotland:theme: Top-Level
      visitscotland:title: Welcome to Business Events Scotland
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>For years Scotland has welcomed the world's greatest thinkers, pioneers, innovators and leaders to the many international congresses, conferences and meetings we host. Scotland is an incredible destination for business events. Our world leading academia, research institutes, industries and innovation centres thrive on ideas, new challenges and the inspiration we can give and draw from delegates to our country.</p>

          <p>In Scotland we believe business events are a catalyst for social and economic transformation; they are a driver to tackle climate change; they are a voice for human rights; they are a leader in the global <a href="https://businessevents.visitscotland.com/why-scotland/journey-to-change/" title="Journey to change">Journey to Change</a>.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: f6ba4bcd-f87d-4145-841d-accd7f2e5152
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2024-01-18T12:31:21.663Z
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2024-01-18T12:31:25.667Z
      hippotranslation:id: f1a75f0d-60a4-49b9-b879-5d143c70353e
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:pswPosition: Hidden
      visitscotland:seoDescription: Welcome to VisitScotland Business Events. Your
        partners in Scotland for conferences, conventions, meetings, incentives and
        more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: Welcome to Business Events Scotland
      visitscotland:teaser: Welcome to VisitScotland Business Events. Your partners
        in Scotland for conferences, conventions, meetings, incentives and more!
      visitscotland:theme: Top-Level
      visitscotland:title: Welcome to Business Events Scotland
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>For years Scotland has welcomed the world's greatest thinkers, pioneers, innovators and leaders to the many international congresses, conferences and meetings we host. Scotland is an incredible destination for business events. Our world leading academia, research institutes, industries and innovation centres thrive on ideas, new challenges and the inspiration we can give and draw from delegates to our country.</p>

          <p>In Scotland we believe business events are a catalyst for social and economic transformation; they are a driver to tackle climate change; they are a voice for human rights; they are a leader in the global <a href="https://businessevents.visitscotland.com/why-scotland/journey-to-change/" title="Journey to change">Journey to Change</a>.</p>
  /demo:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 755121a5-ad27-4c31-ac56-e7a4a2e567ff
    hippostd:foldertype: [new-translated-folder, new-page, new-module]
    hippotranslation:id: 49ff3c38-2146-4b38-b58b-c04d3ce52522
    hippotranslation:locale: en
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: fa32bcd3-1e14-41f5-a871-7caf6d310a19
      /content:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: c6d373a6-da96-4798-acf8-d75adb8658f3
        hippo:availability: []
        hippostd:holder: admin
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2024-01-24T09:57:06.829Z
        hippostdpubwf:lastModificationDate: 2024-01-24T09:57:06.830Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 0944e3ee-1014-4e56-8405-bde96b50c584
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: false
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: ''
        visitscotland:seoNoIndex: false
        visitscotland:seoTitle: ''
        visitscotland:teaser: ''
        visitscotland:theme: Standard
        visitscotland:title: ''
        visitscotland:translation: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
  /be-folder:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 03d2de05-1be7-47b8-8c55-26ea332b999a
    hippostd:foldertype: [new-be-folder, new-be-page, new-be-module]
    hippotranslation:id: 9eb27fc9-4f48-4166-9c54-e555d7f87025
    hippotranslation:locale: en
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 126bf335-fe66-4e1c-b196-64b7cea2aaec
      /content:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 90d943f9-7bd2-4cbe-b510-a152b3c9ead8
        hippo:availability: []
        hippostd:holder: admin
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2024-01-24T09:59:47.719Z
        hippostdpubwf:lastModificationDate: 2024-01-24T09:59:47.719Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: feaad72f-d7d0-4f21-b725-3b93e13d826d
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: false
        visitscotland:pswPosition: Default
        visitscotland:seoDescription: ''
        visitscotland:seoNoIndex: false
        visitscotland:seoTitle: ''
        visitscotland:teaser: ''
        visitscotland:theme: Standard
        visitscotland:title: ''
        visitscotland:translation: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
